H1B Disclosure Dataset: Predicting the case
Status
Problem Statement:
    __The H-1B Dataset selected for this project contains data from employerâ€™s Labor Condition
Application and the case certification determinations processed by the Office of Foreign Labor
Certification (OFLC) where the date of the determination was issued on or after October 1,
2016, and on or before June 30, 2017.
    __The Labor Condition Application (LCA) is a document that a prospective H-1B employer files
with U.S. Department of Labor Employment and Training Administration (DOLETA) when it
seeks to employ nonimmigrant workers at a specific job occupation in an area of intended
employment for not more than three years.
    The goal for this project is to predict the case status of an application submitted by the employer
to hire non-immigrant workers under the H-1B visa program. The employer can hire
non-immigrant workers only after their LCA petition is approved. The approved LCA petition is
then submitted as part of the Petition for a Non-immigrant Worker application for work
authorizations for H-1B visa status.

Download the dataset:
https://drive.google.com/drive/folders/1sIjRnbrIvrDaSkj8TIi-myErAx258iGf?usp=sharing
Data Set Information:
The H-1B dataset from OFLC contained 40 attributes and 528,147 instances.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("H-1B_Disclosure_Data_FY17.csv")

/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (15,16,17,25) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df

,Unnamed: 0,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_BUSINESS_DBA,...,H1B_DEPENDENT,WILLFUL_VIOLATOR,SUPPORT_H1B,LABOR_CON_AGREE,PUBLIC_DISCLOSURE_LOCATION,WORKSITE_CITY,WORKSITE_COUNTY,WORKSITE_STATE,WORKSITE_POSTAL_CODE,ORIGINAL_CERT_DATE
0,0,I-200-16055-173457,CERTIFIED-WITHDRAWN,2016-02-24,2016-10-01,H-1B,2016-08-10,2019-08-10,DISCOVER PRODUCTS INC.,NaN,...,N,N,NaN,Y,NaN,RIVERWOODS,LAKE,IL,60015,2016-03-01
1,1,I-200-16064-557834,CERTIFIED-WITHDRAWN,2016-03-04,2016-10-01,H-1B,2016-08-16,2019-08-16,DFS SERVICES LLC,NaN,...,N,N,NaN,Y,NaN,RIVERWOODS,LAKE,IL,60015,2016-03-08
2,2,I-200-16063-996093,CERTIFIED-WITHDRAWN,2016-03-10,2016-10-01,H-1B,2016-09-09,2019-09-09,EASTBANC TECHNOLOGIES LLC,NaN,...,Y,N,Y,NaN,NaN,WASHINGTON,NaN,DC,20007,2016-03-16
3,3,I-200-16272-196340,WITHDRAWN,2016-09-28,2016-10-01,H-1B,2017-01-26,2020-01-25,INFO SERVICES LLC,NaN,...,Y,N,Y,NaN,NaN,JERSEY CITY,HUDSON,NJ,07302,NaN
4,4,I-200-15053-636744,CERTIFIED-WITHDRAWN,2015-02-22,2016-10-02,H-1B,2015-03-01,2018-03-01,BB&T CORPORATION,NaN,...,N,N,NaN,Y,NaN,NEW YORK,NEW YORK,NY,10036,2015-02-26
5,5,I-200-15071-336195,CERTIFIED-WITHDRAWN,2015-03-12,2016-10-02,H-1B,2015-09-11,2018-09-11,"SUNTRUST BANKS, INC.",NaN,...,N,N,NaN,Y,NaN,ATLANTA,FULTON,GA,30303,2015-03-18
6,6,I-200-16056-842817,CERTIFIED-WITHDRAWN,2016-02-25,2016-10-02,H-1B,2016-08-25,2019-08-24,CITADEL INFORMATION SERVICES INC.,CITADEL,...,Y,N,Y,Y,NaN,EDISON,MIDDLESEX,NJ,08837,2016-03-02
7,7,I-200-16056-757335,CERTIFIED-WITHDRAWN,2016-02-25,2016-10-02,H-1B,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,CITADEL,...,Y,N,Y,Y,NaN,EDISON,MIDDLESEX,NJ,08837,2016-03-02
8,8,I-200-16058-469533,CERTIFIED-WITHDRAWN,2016-02-27,2016-10-02,H-1B,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,CITADEL,...,Y,N,Y,Y,NaN,NEW YORK,NEW YORK,NY,10005,2016-03-03
9,9,I-200-16059-084066,CERTIFIED-WITHDRAWN,2016-02-28,2016-10-02,H-1B,2016-08-29,2019-08-26,CITADEL INFORMATION SERVICES INC.,CITADEL,...,Y,N,Y,Y,NaN,ISELIN,MIDDLESEX,NJ,08830,2016-03-03
10,10,I-200-16060-138258,CERTIFIED-WITHDRAWN,2016-02-29,2016-10-02,H-1B,2016-08-29,2019-08-29,CITADEL INFORMATION SERVICES INC.,CITADEL,...,Y,N,Y,Y,NaN,NEW YORK,NEW YORK,NY,10010,2016-03-04
11,11,I-200-16083-623465,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,NaN,...,Y,N,Y,Y,NaN,PRINCETON,MERCER,NJ,08540,2016-03-29
12,12,I-200-16083-782891,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,NaN,...,Y,N,Y,Y,NaN,NEW BRUNSWICK,MIDDLESEX,NJ,08901,2016-03-29
13,13,I-200-16083-651459,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,NaN,...,Y,N,Y,Y,NaN,NEW BRUNSWICK,MIDDLESEX,NJ,08901,2016-03-29
14,14,I-200-16083-722720,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,NaN,...,Y,N,Y,Y,NaN,NEW BRUNSWICK,MIDDLESEX,NJ,08901,2016-03-29
15,15,I-200-16084-911950,CERTIFIED-WITHDRAWN,2016-03-24,2016-10-02,H-1B,2016-09-23,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,NaN,...,Y,N,Y,Y,NaN,NEW BRUNSWICK,MIDDLESEX,NJ,08901,2016-03-30
16,16,I-200-16276-853235,WITHDRAWN,2016-10-02,2016-10-02,H-1B,2016-10-08,2019-10-07,ITAS INC,NaN,...,N,N,NaN,Y,NaN,MELVILLE,SUFFOLK,NY,11747,NaN
17,17,I-200-13260-552852,CERTIFIED-WITHDRAWN,2013-09-17,2016-10-03,H-1B,2013-12-02,2016-12-01,BATTELLE,NaN,...,N,N,NaN,Y,NaN,RICHLAND,BENTON,WA,99354,2013-09-26
18,18,I-200-13261-450672,CERTIFIED-WITHDRAWN,2013-09-18,2016-10-03,H-1B,2013-10-14,2016-10-13,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,NaN,...,N,N,NaN,Y,NaN,HOUSTON,HARRIS,TX,77099,2013-09-24
19,19,I-200-13261-428354,CERTIFIED-WITHDRAWN,2013-09-18,2016-10-03,H-1B,2013-10-25,2016-10-24,HARMONY SCIENCE ACADEMY-WACO,NaN,...,N,N,NaN,Y,NaN,WACO,MCLENNAN,TX,76710,2013-09-25
20,20,I-200-13266-966905,CERTIFIED-WITHDRAWN,2013-09-23,2016-10-03,H-1B,2013-11-28,2016-11-27,"IDC TECHNOLOGIES, INC.",NaN,...,Y,N,Y,NaN,NaN,MILPITAS,SANTA CLARA,CA,95035,2013-10-21
21,21,I-200-13291-566704,CERTIFIED-WITHDRAWN,2013-10-18,2016-10-03,H-1B,2013-12-02,2016-12-01,BATTELLE,NaN,...,N,N,NaN,Y,NaN,RICHLAND,BENTON,WA,99354,2013-10-26
22,22,I-200-13294-544059,CERTIFIED-WITHDRAWN,2013-10-21,2016-10-03,H-1B,2014-03-01,2017-02-28,OREGON HEALTH & SCIENCE UNIVERSITY,NaN,...,N,N,NaN,NaN,NaN,PORTLAND,MULTNOMAH,OR,97239,2013-10-26
23,23,I-200-13297-849893,CERTIFIED-WITHDRAWN,2013-10-24,2016-10-03,H-1B,2013-11-23,2016-11-22,GIMMAL LLC,NaN,...,N,N,NaN,NaN,NaN,HOUSTON,HARRIS,TX,77046,2013-11-01
24,24,I-200-13338-801657,CERTIFIED-WITHDRAWN,2013-12-04,2016-10-03,H-1B,2014-01-01,2016-12-31,HARMONY SCIENCE ACADEMY-EULESS,NaN,...,N,N,NaN,Y,NaN,EULESS,TARRANT,TX,76040,2013-12-10
25,25,I-200-13353-669114,CERTIFIED-WITHDRAWN,2013-12-23,2016-10-03,H-1B,2013-12-27,2016-12-26,"PLANTRONICS, INC.",NaN,...,N,N,NaN,NaN,NaN,AUSTIN,TRAVIS,TX,78704,2013-12-30
26,26,I-200-13357-734910,CERTIFIED-WITHDRAWN,2013-12-23,2016-10-03,H-1B,2014-05-11,2017-05-10,THE UNIVERSITY OF CHICAGO,NaN,...,N,N,NaN,NaN,NaN,CHICAGO,COOK,IL,60637,2013-12-30
27,27,I-200-14051-198952,CERTIFIED-WITHDRAWN,2014-02-24,2016-10-03,H-1B,2014-04-15,2017-04-14,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",NaN,...,N,N,NaN,N,NaN,LOS ANGELES,LOS ANGELES,CA,90095,2014-02-28
28,28,I-200-14052-116073,CERTIFIED-WITHDRAWN,2014-02-26,2016-10-03,H-1B,2014-08-24,2017-08-23,"AXCESS FINANCIAL SERVICES, INC.",NaN,...,N,N,NaN,NaN,NaN,CINCINNATI,HAMILTON,OH,45236,2014-03-04
29,29,I-200-14058-790431,CERTIFIED-WITHDRAWN,2014-02-27,2016-10-03,H-1B,2014-06-07,2017-06-06,WASHINGTON STATE UNIVERSITY,NaN,...,N,N,NaN,NaN,NaN,PULLMAN,WHITMAN,WA,99164,2014-03-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,624620,I-203-17269-466479,DENIED,2017-09-28,2017-09-29,E-3 Australian,2017-11-01,2019-11-01,ELLIOTT MANAGEMENT CORPORATION,NaN,...,NaN,NaN,NaN,NaN,NaN,NEW YORK,NEW YORK,NY,10019,NaN
624621,624621,I-200-17271-642943,WITHDRAWN,2017-09-28,2017-09-29,H-1B,2017-12-19,2020-12-18,I NET SOFTWARE TECHNOLOGIES INC,NaN,...,Y,N,Y,NaN,NaN,FT WORTH,TARRANT,TX,76117,NaN
624622,624622,I-200-17272-196859,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",NaN,...,N,N,NaN,Y,NaN,IRVING,DALLAS,TX,75039,NaN
624623,624623,I-200-17272-639031,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2019-11-07,"FRONTIER TECHNOLOGIES, LLC",NaN,...,Y,N,Y,NaN,NaN,ELK GROVE VILLAGE,COOK,IL,60007,NaN
624624,624624,I-200-17272-721703,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2018-05-01,AVANI TECHNOLOGY SOLUTIONS INC.,NaN,...,Y,N,Y,Y,NaN,HOLLAND,OTTAWA,MI,49423,NaN
624625,624625,I-200-17272-661664,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",NaN,...,N,N,NaN,Y,NaN,IRVING,DALLAS,TX,75039,NaN
624626,624626,I-200-17272-128765,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-09,2020-12-08,PHILIPS NORTH AMERICA LLC,NaN,...,N,N,NaN,NaN,NaN,PLEASANTON,ALAMEDA,CA,94588-3050,NaN
624627,624627,I-200-17272-445626,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,"AMPCUS, INC.",NaN,...,N,N,NaN,NaN,NaN,RESTON,FAIRFAX COUNTY,VA,20190,NaN
624628,624628,I-200-17272-979954,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-10,2020-10-09,VIGILANT TECHNOLOGIES LLC,NaN,...,Y,N,Y,Y,NaN,TROY,OAKLAND,MI,48084,NaN
624629,624629,I-200-17272-573030,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-16,2020-10-15,"ZUORA, INC.",NaN,...,N,N,NaN,NaN,NaN,SAN JOSE,SANTA CLARA,CA,95134,NaN
624630,624630,I-200-17262-848935,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-18,2018-12-17,WASHINGTON UNIVERSITY IN ST. LOUIS,NaN,...,N,N,NaN,NaN,NaN,SAINT LOUIS,SAINT LOUIS,MO,63110,NaN
624631,624631,I-200-17272-440643,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2020-09-28,"ARTEMIS CONSULTING, INC.",NaN,...,N,N,NaN,NaN,NaN,WASHINGTON,DISTRICT OF COLUMBIA,DC,20002,NaN
624632,624632,I-200-17271-240450,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-11,2020-10-11,BANK OF AMERICA N.A.,NaN,...,N,N,NaN,NaN,NaN,NEW YORK,NEW YORK,NY,10036,NaN
624633,624633,I-200-17269-336006,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-11,2020-08-16,"HALLIBURTON ENERGY SERVICES, INC.",NaN,...,N,N,NaN,NaN,NaN,HOUSTON,HARRIS,TX,77032,NaN
624634,624634,I-200-17271-148414,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-30,2020-10-29,"ADVANCED MICRO DEVICES, INC.",NaN,...,N,N,NaN,Y,NaN,SUNNYVALE,SANTA CLARA,CA,94088,NaN
624635,624635,I-200-17272-382469,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2020-10-08,CONSUMERINFO.COM,NaN,...,N,N,NaN,NaN,NaN,COSTA MESA,ORANGE,CA,92626,NaN
624636,624636,I-200-17272-505596,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-13,2019-12-12,"MICHAEL MALTZAN ARCHITECTURE, INC.",NaN,...,N,N,NaN,NaN,NaN,LOS ANGELES,LOS ANGELES,CA,90027,NaN
624637,624637,I-200-17272-643010,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,L&T TECHNOLOGY SERVICES LIMITED,NaN,...,Y,N,Y,NaN,NaN,EL SEGUNDO,LOS ANGELES,CA,90245,NaN
624638,624638,I-200-17272-062244,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-04,2020-10-03,"HCL AMERICA, INC.",NaN,...,Y,N,Y,NaN,NaN,MOUNDS VIEW,RAMSEY,MN,55112,NaN
624639,624639,I-200-17272-197048,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2020-09-28,TECHNOSOFT GROUP INC,NaN,...,Y,N,Y,NaN,NaN,EAGAN,DAKOTA,MN,55121,NaN
624640,624640,I-200-17272-228501,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2020-10-09,"FRONTIER TECHNOLOGIES, LLC",NaN,...,Y,N,Y,NaN,NaN,WATERTOWN,MIDDLESEX,MA,02472,NaN
624641,624641,I-200-17270-987890,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,"CASA SYSTEMS, INC.",NaN,...,N,N,NaN,NaN,NaN,ANDOVER,ESSEX,MA,01810,NaN
624642,624642,I-200-15112-109700,CERTIFIED-WITHDRAWN,2015-05-04,2017-09-30,H-1B,2015-10-02,2018-10-01,"STLPORT CONSULTING, INC.",NaN,...,N,N,NaN,NaN,NaN,MOUNTAIN VIEW,SANTA CLARA,CA,94043,2015-05-08
624643,624643,I-200-15212-709534,CERTIFIED-WITHDRAWN,2015-07-31,2017-09-30,H-1B,2015-08-01,2018-07-31,"STLPORT CONSULTING, INC.",NaN,...,N,N,NaN,NaN,NaN,MOUNTAIN VIEW,SANTA CLARA,CA,94043,2015-08-06
624644,624644,I-200-15223-797576,CERTIFIED-WITHDRAWN,2015-08-11,2017-09-30,H-1B,2015-08-11,2018-07-31,"STLPORT CONSULTING, INC.",NaN,...,N,N,NaN,NaN,NaN,MOUNTAIN VIEW,SANTA CLARA,CA,94043,2015-08-17
624645,624645,I-200-16188-449352,CERTIFIED-WITHDRAWN,2016-07-06,2017-09-30,H-1B,2016-07-06,2019-07-05,FAST SWITCH LTD,NaN,...,Y,N,Y,NaN,NaN,DUBLIN,FRANKLIN,OH,43017,2016-07-12
624646,624646,I-200-16309-239165,CERTIFIED,2016-11-04,2016-11-10,H-1B,2016-12-01,2017-11-30,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,NaN,...,N,N,NaN,Y,NaN,CAMBRIDGE,MIDDLESEX,MA,02139,2016-11-10
624647,624647,I-200-16363-692687,CERTIFIED,2016-12-28,2017-01-04,H-1B,2017-02-01,2018-01-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,NaN,...,N,N,NaN,Y,NaN,CAMBRIDGE,MIDDLESEX,MA,02139,2017-01-04
624648,624648,I-200-17055-511599,CERTIFIED,2017-02-24,2017-03-02,H-1B,2017-06-01,2018-05-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,NaN,...,N,N,NaN,Y,NaN,CAMBRIDGE,MIDDLESEX,MA,02139,2017-03-02
624649,624649,I-200-17068-828736,CERTIFIED,2017-03-09,2017-03-15,H-1B,2017-09-08,2020-09-08,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",NaN,...,N,N,NaN,NaN,NaN,BEVERLY HILLS,LOS ANGELES,CA,90210,2017-03-15

In [5]:
df.shape

(624650, 53)

In [6]:
df.CASE_STATUS.value_counts()

CERTIFIED              545694
CERTIFIED-WITHDRAWN     49704
WITHDRAWN               20772
DENIED                   8480
Name: CASE_STATUS, dtype: int64

In [11]:
(df.isnull().sum()/len(df))*100

Unnamed: 0                       0.000000
CASE_NUMBER                      0.000000
CASE_STATUS                      0.000000
CASE_SUBMITTED                   0.000000
DECISION_DATE                    0.000000
VISA_CLASS                       0.000000
EMPLOYMENT_START_DATE            0.004643
EMPLOYMENT_END_DATE              0.004803
EMPLOYER_NAME                    0.008965
EMPLOYER_BUSINESS_DBA           93.072921
EMPLOYER_ADDRESS                 0.001121
EMPLOYER_CITY                    0.002401
EMPLOYER_STATE                   0.002882
EMPLOYER_POSTAL_CODE             0.002882
EMPLOYER_COUNTRY                15.449772
EMPLOYER_PROVINCE               99.020892
EMPLOYER_PHONE                  15.449932
EMPLOYER_PHONE_EXT              95.537981
AGENT_REPRESENTING_EMPLOYER     15.449612
AGENT_ATTORNEY_NAME              0.000000
AGENT_ATTORNEY_CITY             43.753462
AGENT_ATTORNEY_STATE            46.208437
JOB_TITLE                        0.000800
SOC_CODE                         0.000320
SOC_NAME                         0.000480
NAICS_CODE                       0.001121
TOTAL_WORKERS                    0.000000
NEW_EMPLOYMENT                   0.000000
CONTINUED_EMPLOYMENT             0.000000
CHANGE_PREVIOUS_EMPLOYMENT       0.000000
NEW_CONCURRENT_EMPLOYMENT        0.000000
CHANGE_EMPLOYER                  0.000000
AMENDED_PETITION                 0.000000
FULL_TIME_POSITION               0.000800
PREVAILING_WAGE                  0.000160
PW_UNIT_OF_PAY                   0.007364
PW_WAGE_LEVEL                   19.806292
PW_SOURCE                        0.007364
PW_SOURCE_YEAR                   0.007204
PW_SOURCE_OTHER                  1.020091
WAGE_RATE_OF_PAY_FROM            0.000000
WAGE_RATE_OF_PAY_TO              0.000160
WAGE_UNIT_OF_PAY                 0.001281
H1B_DEPENDENT                    2.199952
WILLFUL_VIOLATOR                 2.200432
SUPPORT_H1B                     61.502281
LABOR_CON_AGREE                 60.782038
PUBLIC_DISCLOSURE_LOCATION     100.000000
WORKSITE_CITY                    0.002081
WORKSITE_COUNTY                  0.188746
WORKSITE_STATE                   0.001441
WORKSITE_POSTAL_CODE             0.003042
ORIGINAL_CERT_DATE              92.042264
dtype: float64

In [ ]:
# df.drop(columns=["Unnamed: 0,EMPLOYER_BUSINESS_DBA,ORIGINAL_CERT_DATE,EMPLOYER_PROVINCE,EMPLOYER_PHONE_EXT,"])

In [15]:
df1 = df.dropna(thresh=df.shape[0]*0.6,how='all',axis=1)
df1=df1.drop(columns=["Unnamed: 0"])

In [16]:
df1

,CASE_NUMBER,CASE_STATUS,CASE_SUBMITTED,DECISION_DATE,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_ADDRESS,EMPLOYER_CITY,...,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_CITY,WORKSITE_COUNTY,WORKSITE_STATE,WORKSITE_POSTAL_CODE
0,I-200-16055-173457,CERTIFIED-WITHDRAWN,2016-02-24,2016-10-01,H-1B,2016-08-10,2019-08-10,DISCOVER PRODUCTS INC.,2500 LAKE COOK ROAD,RIVERWOODS,...,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,RIVERWOODS,LAKE,IL,60015
1,I-200-16064-557834,CERTIFIED-WITHDRAWN,2016-03-04,2016-10-01,H-1B,2016-08-16,2019-08-16,DFS SERVICES LLC,2500 LAKE COOK ROAD,RIVERWOODS,...,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,RIVERWOODS,LAKE,IL,60015
2,I-200-16063-996093,CERTIFIED-WITHDRAWN,2016-03-10,2016-10-01,H-1B,2016-09-09,2019-09-09,EASTBANC TECHNOLOGIES LLC,1211 31ST ST. NW,WASHINGTON,...,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,WASHINGTON,NaN,DC,20007
3,I-200-16272-196340,WITHDRAWN,2016-09-28,2016-10-01,H-1B,2017-01-26,2020-01-25,INFO SERVICES LLC,17177 NORTH LAUREL PARK DR,LIVONIA,...,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,JERSEY CITY,HUDSON,NJ,07302
4,I-200-15053-636744,CERTIFIED-WITHDRAWN,2015-02-22,2016-10-02,H-1B,2015-03-01,2018-03-01,BB&T CORPORATION,223 WEST NASH STREET,WILSON,...,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,NEW YORK,NEW YORK,NY,10036
5,I-200-15071-336195,CERTIFIED-WITHDRAWN,2015-03-12,2016-10-02,H-1B,2015-09-11,2018-09-11,"SUNTRUST BANKS, INC.","303 PEACHTREE STREET, NE",ATLANTA,...,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,ATLANTA,FULTON,GA,30303
6,I-200-16056-842817,CERTIFIED-WITHDRAWN,2016-02-25,2016-10-02,H-1B,2016-08-25,2019-08-24,CITADEL INFORMATION SERVICES INC.,33 WOOD AVENUE SOUTH,ISELIN,...,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,EDISON,MIDDLESEX,NJ,08837
7,I-200-16056-757335,CERTIFIED-WITHDRAWN,2016-02-25,2016-10-02,H-1B,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,33 WOOD AVENUE SOUTH,ISELIN,...,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,EDISON,MIDDLESEX,NJ,08837
8,I-200-16058-469533,CERTIFIED-WITHDRAWN,2016-02-27,2016-10-02,H-1B,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,33 WOOD AVENUE SOUTH,ISELIN,...,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,NEW YORK,NEW YORK,NY,10005
9,I-200-16059-084066,CERTIFIED-WITHDRAWN,2016-02-28,2016-10-02,H-1B,2016-08-29,2019-08-26,CITADEL INFORMATION SERVICES INC.,33 WOOD AVENUE SOUTH,ISELIN,...,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,ISELIN,MIDDLESEX,NJ,08830
10,I-200-16060-138258,CERTIFIED-WITHDRAWN,2016-02-29,2016-10-02,H-1B,2016-08-29,2019-08-29,CITADEL INFORMATION SERVICES INC.,33 WOOD AVENUE SOUTH,ISELIN,...,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,NEW YORK,NEW YORK,NY,10010
11,I-200-16083-623465,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,666 PLAINSBORO RD,PLAINSBORO,...,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,PRINCETON,MERCER,NJ,08540
12,I-200-16083-782891,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,666 PLAINSBORO RD,PLAINSBORO,...,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,NEW BRUNSWICK,MIDDLESEX,NJ,08901
13,I-200-16083-651459,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,666 PLAINSBORO RD,PLAINSBORO,...,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,NEW BRUNSWICK,MIDDLESEX,NJ,08901
14,I-200-16083-722720,CERTIFIED-WITHDRAWN,2016-03-23,2016-10-02,H-1B,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,666 PLAINSBORO RD,PLAINSBORO,...,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,NEW BRUNSWICK,MIDDLESEX,NJ,08901
15,I-200-16084-911950,CERTIFIED-WITHDRAWN,2016-03-24,2016-10-02,H-1B,2016-09-23,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,666 PLAINSBORO RD,PLAINSBORO,...,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,NEW BRUNSWICK,MIDDLESEX,NJ,08901
16,I-200-16276-853235,WITHDRAWN,2016-10-02,2016-10-02,H-1B,2016-10-08,2019-10-07,ITAS INC,8888 KEYSTONE CROSSING,INDIANAPOLIS,...,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,MELVILLE,SUFFOLK,NY,11747
17,I-200-13260-552852,CERTIFIED-WITHDRAWN,2013-09-17,2016-10-03,H-1B,2013-12-02,2016-12-01,BATTELLE,902 BATTELLE BLVD,RICHLAND,...,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,RICHLAND,BENTON,WA,99354
18,I-200-13261-450672,CERTIFIED-WITHDRAWN,2013-09-18,2016-10-03,H-1B,2013-10-14,2016-10-13,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,9431 W SAM HOUSTON PKWY S,HOUSTON,...,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,HOUSTON,HARRIS,TX,77099
19,I-200-13261-428354,CERTIFIED-WITHDRAWN,2013-09-18,2016-10-03,H-1B,2013-10-25,2016-10-24,HARMONY SCIENCE ACADEMY-WACO,1900 N VALLEY MILLS DR.,WACO,...,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,WACO,MCLENNAN,TX,76710
20,I-200-13266-966905,CERTIFIED-WITHDRAWN,2013-09-23,2016-10-03,H-1B,2013-11-28,2016-11-27,"IDC TECHNOLOGIES, INC.",1851 MCCARTHY BLVD,MILPITAS,...,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,MILPITAS,SANTA CLARA,CA,95035
21,I-200-13291-566704,CERTIFIED-WITHDRAWN,2013-10-18,2016-10-03,H-1B,2013-12-02,2016-12-01,BATTELLE,902 BATTELLE BLVD,RICHLAND,...,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,RICHLAND,BENTON,WA,99354
22,I-200-13294-544059,CERTIFIED-WITHDRAWN,2013-10-21,2016-10-03,H-1B,2014-03-01,2017-02-28,OREGON HEALTH & SCIENCE UNIVERSITY,"3181 S.W. SAM JACKSON PARK ROAD, L349",PORTLAND,...,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,PORTLAND,MULTNOMAH,OR,97239
23,I-200-13297-849893,CERTIFIED-WITHDRAWN,2013-10-24,2016-10-03,H-1B,2013-11-23,2016-11-22,GIMMAL LLC,"24 GREENWAY PLAZA, SUITE 1000",HOUSTON,...,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,HOUSTON,HARRIS,TX,77046
24,I-200-13338-801657,CERTIFIED-WITHDRAWN,2013-12-04,2016-10-03,H-1B,2014-01-01,2016-12-31,HARMONY SCIENCE ACADEMY-EULESS,701 S. INDUSTRIAL BLVD,EULESS,...,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,EULESS,TARRANT,TX,76040
25,I-200-13353-669114,CERTIFIED-WITHDRAWN,2013-12-23,2016-10-03,H-1B,2013-12-27,2016-12-26,"PLANTRONICS, INC.",345 ENCINAL STREET,SANTA CRUZ,...,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,AUSTIN,TRAVIS,TX,78704
26,I-200-13357-734910,CERTIFIED-WITHDRAWN,2013-12-23,2016-10-03,H-1B,2014-05-11,2017-05-10,THE UNIVERSITY OF CHICAGO,OFFICE OF INTERNATIONAL AFFAIRS,CHICAGO,...,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,CHICAGO,COOK,IL,60637
27,I-200-14051-198952,CERTIFIED-WITHDRAWN,2014-02-24,2016-10-03,H-1B,2014-04-15,2017-04-14,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",106 BRADLEY INTERNATIONAL HALL,LOS ANGELES,...,NaN,47244.00,0.0,Year,N,N,LOS ANGELES,LOS ANGELES,CA,90095
28,I-200-14052-116073,CERTIFIED-WITHDRAWN,2014-02-26,2016-10-03,H-1B,2014-08-24,2017-08-23,"AXCESS FINANCIAL SERVICES, INC.",7755 MONTGOMERY ROAD,CINCINNATI,...,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,CINCINNATI,HAMILTON,OH,45236
29,I-200-14058-790431,CERTIFIED-WITHDRAWN,2014-02-27,2016-10-03,H-1B,2014-06-07,2017-06-06,WASHINGTON STATE UNIVERSITY,"WASHINGTON STATE UNIV., INT'L PROGS-GLOBAL SERV",PULLMAN,...,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,PULLMAN,WHITMAN,WA,99164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,I-203-17269-466479,DENIED,2017-09-28,2017-09-29,E-3 Australian,2017-11-01,2019-11-01,ELLIOTT MANAGEMENT CORPORATION,40 WEST 57TH STREET,NEW YORK,...,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,NaN,NaN,NEW YORK,NEW YORK,NY,10019
624621,I-200-17271-642943,WITHDRAWN,2017-09-28,2017-09-29,H-1B,2017-12-19,2020-12-18,I NET SOFTWARE TECHNOLOGIES INC,9901 VALLEY RANCH PKWY E,IRVING,...,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,FT WORTH,TARRANT,TX,76117
624622,I-200-17272-196859,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",2300 WEST PLANO PARKWAY,PLANO,...,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,IRVING,DALLAS,TX,75039
624623,I-200-17272-639031,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2019-11-07,"FRONTIER TECHNOLOGIES, LLC",602 WEST FIFTH AVENUE,NAPERVILLE,...,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,ELK GROVE VILLAGE,COOK,IL,60007
624624,I-200-17272-721703,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2018-05-01,AVANI TECHNOLOGY SOLUTIONS INC.,687 LEE ROAD,ROCHESTER,...,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,HOLLAND,OTTAWA,MI,49423
624625,I-200-17272-661664,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",2300 WEST PLANO PARKWAY,PLANO,...,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,IRVING,DALLAS,TX,75039
624626,I-200-17272-128765,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-09,2020-12-08,PHILIPS NORTH AMERICA LLC,3000 MINUTEMAN ROAD,ANDOVER,...,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,PLEASANTON,ALAMEDA,CA,94588-3050
624627,I-200-17272-445626,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,"AMPCUS, INC.",14900 CONFERENCE CENTER DRIVE,CHANTILLY,...,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,RESTON,FAIRFAX COUNTY,VA,20190
624628,I-200-17272-979954,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-10,2020-10-09,VIGILANT TECHNOLOGIES LLC,3290 W BIG BEAVER RD,TROY,...,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,TROY,OAKLAND,MI,48084
624629,I-200-17272-573030,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-16,2020-10-15,"ZUORA, INC.",3050 SOUTH DELAWARE STREET,SAN MATEO,...,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,SAN JOSE,SANTA CLARA,CA,95134
624630,I-200-17262-848935,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-18,2018-12-17,WASHINGTON UNIVERSITY IN ST. LOUIS,ONE BROOKINGS DRIVE,ST. LOUIS,...,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,SAINT LOUIS,SAINT LOUIS,MO,63110
624631,I-200-17272-440643,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2020-09-28,"ARTEMIS CONSULTING, INC.",2669 OAKTON GLEN DR.,VIENNA,...,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,WASHINGTON,DISTRICT OF COLUMBIA,DC,20002
624632,I-200-17271-240450,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-11,2020-10-11,BANK OF AMERICA N.A.,50 ROCKEFELLER PLAZA,NEW YORK,...,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,NEW YORK,NEW YORK,NY,10036
624633,I-200-17269-336006,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-11,2020-08-16,"HALLIBURTON ENERGY SERVICES, INC.",3000 N. SAM HOUSTON PARKWAY EAST,HOUSTON,...,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,HOUSTON,HARRIS,TX,77032
624634,I-200-17271-148414,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-30,2020-10-29,"ADVANCED MICRO DEVICES, INC.",ONE AMD PLACE,SUNNYVALE,...,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,SUNNYVALE,SANTA CLARA,CA,94088
624635,I-200-17272-382469,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2020-10-08,CONSUMERINFO.COM,475 ANTON BLVD.,COSTA MESA,...,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,COSTA MESA,ORANGE,CA,92626
624636,I-200-17272-505596,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-12-13,2019-12-12,"MICHAEL MALTZAN ARCHITECTURE, INC.",2801 HYPERION AVENUE,LOS ANGELES,...,NaN,87000.00,0.0,Year,N,N,LOS ANGELES,LOS ANGELES,CA,90027
624637,I-200-17272-643010,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,L&T TECHNOLOGY SERVICES LIMITED,2035 LINCOLN HIGHWAY,EDISON,...,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,EL SEGUNDO,LOS ANGELES,CA,90245
624638,I-200-17272-062244,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-04,2020-10-03,"HCL AMERICA, INC.",330 POTRERO AVENUE,SUNNYVALE,...,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,MOUNDS VIEW,RAMSEY,MN,55112
624639,I-200-17272-197048,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-09-29,2020-09-28,TECHNOSOFT GROUP INC,2300 VALLEY VIEW LANE,IRVING,...,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,EAGAN,DAKOTA,MN,55121
624640,I-200-17272-228501,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-09,2020-10-09,"FRONTIER TECHNOLOGIES, LLC",602 WEST FIFTH AVENUE,NAPERVILLE,...,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,WATERTOWN,MIDDLESEX,MA,02472
624641,I-200-17270-987890,WITHDRAWN,2017-09-29,2017-09-29,H-1B,2017-10-06,2020-10-05,"CASA SYSTEMS, INC.",100 OLD RIVER ROAD,ANDOVER,...,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,ANDOVER,ESSEX,MA,01810
624642,I-200-15112-109700,CERTIFIED-WITHDRAWN,2015-05-04,2017-09-30,H-1B,2015-10-02,2018-10-01,"STLPORT CONSULTING, INC.",1077 INDEPENDENCE AVENUE,MOUNTAIN VIEW,...,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,MOUNTAIN VIEW,SANTA CLARA,CA,94043
624643,I-200-15212-709534,CERTIFIED-WITHDRAWN,2015-07-31,2017-09-30,H-1B,2015-08-01,2018-07-31,"STLPORT CONSULTING, INC.",1077 INDEPENDENCE AVENUE,MOUNTAIN VIEW,...,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,MOUNTAIN VIEW,SANTA CLARA,CA,94043
624644,I-200-15223-797576,CERTIFIED-WITHDRAWN,2015-08-11,2017-09-30,H-1B,2015-08-11,2018-07-31,"STLPORT CONSULTING, INC.",1077 INDEPENDENCE AVENUE,MOUNTAIN VIEW,...,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,MOUNTAIN VIEW,SANTA CLARA,CA,94043
624645,I-200-16188-449352,CERTIFIED-WITHDRAWN,2016-07-06,2017-09-30,H-1B,2016-07-06,2019-07-05,FAST SWITCH LTD,4900 BLAZER PARKWAY,DUBLIN,...,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,DUBLIN,FRANKLIN,OH,43017
624646,I-200-16309-239165,CERTIFIED,2016-11-04,2016-11-10,H-1B,2016-12-01,2017-11-30,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,...,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
624647,I-200-16363-692687,CERTIFIED,2016-12-28,2017-01-04,H-1B,2017-02-01,2018-01-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,...,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
624648,I-200-17055-511599,CERTIFIED,2017-02-24,2017-03-02,H-1B,2017-06-01,2018-05-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,77 MASSACHUSETTS AVENUE,CAMBRIDGE,...,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,CAMBRIDGE,MIDDLESEX,MA,02139
624649,I-200-17068-828736,CERTIFIED,2017-03-09,2017-03-15,H-1B,2017-09-08,2020-09-08,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",9440 SANTA MONICA BLVD,BEVERLY HILLS,...,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,BEVERLY HILLS,LOS ANGELES,CA,90210

In [17]:
(df1.isnull().sum()/len(df1))*100

CASE_NUMBER                     0.000000
CASE_STATUS                     0.000000
CASE_SUBMITTED                  0.000000
DECISION_DATE                   0.000000
VISA_CLASS                      0.000000
EMPLOYMENT_START_DATE           0.004643
EMPLOYMENT_END_DATE             0.004803
EMPLOYER_NAME                   0.008965
EMPLOYER_ADDRESS                0.001121
EMPLOYER_CITY                   0.002401
EMPLOYER_STATE                  0.002882
EMPLOYER_POSTAL_CODE            0.002882
EMPLOYER_COUNTRY               15.449772
EMPLOYER_PHONE                 15.449932
AGENT_REPRESENTING_EMPLOYER    15.449612
AGENT_ATTORNEY_NAME             0.000000
JOB_TITLE                       0.000800
SOC_CODE                        0.000320
SOC_NAME                        0.000480
NAICS_CODE                      0.001121
TOTAL_WORKERS                   0.000000
NEW_EMPLOYMENT                  0.000000
CONTINUED_EMPLOYMENT            0.000000
CHANGE_PREVIOUS_EMPLOYMENT      0.000000
NEW_CONCURRENT_EMPLOYMENT       0.000000
CHANGE_EMPLOYER                 0.000000
AMENDED_PETITION                0.000000
FULL_TIME_POSITION              0.000800
PREVAILING_WAGE                 0.000160
PW_UNIT_OF_PAY                  0.007364
PW_WAGE_LEVEL                  19.806292
PW_SOURCE                       0.007364
PW_SOURCE_YEAR                  0.007204
PW_SOURCE_OTHER                 1.020091
WAGE_RATE_OF_PAY_FROM           0.000000
WAGE_RATE_OF_PAY_TO             0.000160
WAGE_UNIT_OF_PAY                0.001281
H1B_DEPENDENT                   2.199952
WILLFUL_VIOLATOR                2.200432
WORKSITE_CITY                   0.002081
WORKSITE_COUNTY                 0.188746
WORKSITE_STATE                  0.001441
WORKSITE_POSTAL_CODE            0.003042
dtype: float64

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624650 entries, 0 to 624649
Data columns (total 43 columns):
CASE_NUMBER                    624650 non-null object
CASE_STATUS                    624650 non-null object
CASE_SUBMITTED                 624650 non-null object
DECISION_DATE                  624650 non-null object
VISA_CLASS                     624650 non-null object
EMPLOYMENT_START_DATE          624621 non-null object
EMPLOYMENT_END_DATE            624620 non-null object
EMPLOYER_NAME                  624594 non-null object
EMPLOYER_ADDRESS               624643 non-null object
EMPLOYER_CITY                  624635 non-null object
EMPLOYER_STATE                 624632 non-null object
EMPLOYER_POSTAL_CODE           624632 non-null object
EMPLOYER_COUNTRY               528143 non-null object
EMPLOYER_PHONE                 528142 non-null object
AGENT_REPRESENTING_EMPLOYER    528144 non-null object
AGENT_ATTORNEY_NAME            624650 non-null object
JOB_TITLE                      624645 non-null object
SOC_CODE                       624648 non-null object
SOC_NAME                       624647 non-null object
NAICS_CODE                     624643 non-null object
TOTAL_WORKERS                  624650 non-null int64
NEW_EMPLOYMENT                 624650 non-null int64
CONTINUED_EMPLOYMENT           624650 non-null int64
CHANGE_PREVIOUS_EMPLOYMENT     624650 non-null int64
NEW_CONCURRENT_EMPLOYMENT      624650 non-null int64
CHANGE_EMPLOYER                624650 non-null int64
AMENDED_PETITION               624650 non-null int64
FULL_TIME_POSITION             624645 non-null object
PREVAILING_WAGE                624649 non-null float64
PW_UNIT_OF_PAY                 624604 non-null object
PW_WAGE_LEVEL                  500930 non-null object
PW_SOURCE                      624604 non-null object
PW_SOURCE_YEAR                 624605 non-null float64
PW_SOURCE_OTHER                618278 non-null object
WAGE_RATE_OF_PAY_FROM          624650 non-null float64
WAGE_RATE_OF_PAY_TO            624649 non-null float64
WAGE_UNIT_OF_PAY               624642 non-null object
H1B_DEPENDENT                  610908 non-null object
WILLFUL_VIOLATOR               610905 non-null object
WORKSITE_CITY                  624637 non-null object
WORKSITE_COUNTY                623471 non-null object
WORKSITE_STATE                 624641 non-null object
WORKSITE_POSTAL_CODE           624631 non-null object
dtypes: float64(4), int64(7), object(32)
memory usage: 204.9+ MB

In [30]:
df1[["EMPLOYER_COUNTRY","EMPLOYER_PHONE","AGENT_REPRESENTING_EMPLOYER"]].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 624650 entries, 0 to 624649
Data columns (total 3 columns):
EMPLOYER_COUNTRY               528143 non-null object
EMPLOYER_PHONE                 528142 non-null object
AGENT_REPRESENTING_EMPLOYER    528144 non-null object
dtypes: object(3)
memory usage: 14.3+ MB

In [32]:
df.shape[0]*0.60

374790.0

In [37]:
df.EMPLOYER_PHONE

0          2244050900
1          2244050900
2          2022953000
3          7343776007
4          2522462031
5          4048137888
6          7322380072
7          7322380072
8          7322380072
9          7322380072
10         7322380072
11         6092695555
12         6092695555
13         6092695555
14         6092695555
15         6092695555
16         3175758950
17         5093753959
18         7134920214
19         2547517878
20         4083830155
21         5093753959
22         5034942169
23         7135866500
24         8173543000
25         8314584458
26         7737027752
27         3108251681
28         5132296469
29         5093354508
             ...
624620            NaN
624621            NaN
624622            NaN
624623            NaN
624624            NaN
624625            NaN
624626            NaN
624627            NaN
624628            NaN
624629            NaN
624630            NaN
624631            NaN
624632            NaN
624633            NaN
624634            NaN
624635            NaN
624636            NaN
624637            NaN
624638            NaN
624639            NaN
624640            NaN
624641            NaN
624642            NaN
624643            NaN
624644            NaN
624645            NaN
624646    6.17253e+09
624647    6.17253e+09
624648    6.17253e+09
624649    3.10286e+09
Name: EMPLOYER_PHONE, Length: 624650, dtype: object

In [38]:
df2 = df1.copy(deep=True)

In [39]:
df2 = df2.replace(np.nan, 0)

In [57]:
df2=df2.drop(columns=["CASE_NUMBER"])

In [66]:
df2["DECISION_DATE"]=pd.to_datetime(df2["DECISION_DATE"])
df2["CASE_SUBMITTED"]=pd.to_datetime(df2["CASE_SUBMITTED"])

In [67]:
import datetime as dt
df2['Time_to_Review'] = (df2['DECISION_DATE']-df2['CASE_SUBMITTED']).dt.days

In [70]:
df2=df2.drop(columns=["DECISION_DATE","CASE_SUBMITTED"])

In [71]:
df2.columns

Index(['CASE_STATUS', 'VISA_CLASS', 'EMPLOYMENT_START_DATE',
       'EMPLOYMENT_END_DATE', 'EMPLOYER_NAME', 'EMPLOYER_ADDRESS',
       'EMPLOYER_CITY', 'EMPLOYER_STATE', 'EMPLOYER_POSTAL_CODE',
       'EMPLOYER_COUNTRY', 'EMPLOYER_PHONE', 'AGENT_REPRESENTING_EMPLOYER',
       'AGENT_ATTORNEY_NAME', 'JOB_TITLE', 'SOC_CODE', 'SOC_NAME',
       'NAICS_CODE', 'TOTAL_WORKERS', 'NEW_EMPLOYMENT', 'CONTINUED_EMPLOYMENT',
       'CHANGE_PREVIOUS_EMPLOYMENT', 'NEW_CONCURRENT_EMPLOYMENT',
       'CHANGE_EMPLOYER', 'AMENDED_PETITION', 'FULL_TIME_POSITION',
       'PREVAILING_WAGE', 'PW_UNIT_OF_PAY', 'PW_WAGE_LEVEL', 'PW_SOURCE',
       'PW_SOURCE_YEAR', 'PW_SOURCE_OTHER', 'WAGE_RATE_OF_PAY_FROM',
       'WAGE_RATE_OF_PAY_TO', 'WAGE_UNIT_OF_PAY', 'H1B_DEPENDENT',
       'WILLFUL_VIOLATOR', 'WORKSITE_CITY', 'WORKSITE_COUNTY',
       'WORKSITE_STATE', 'WORKSITE_POSTAL_CODE', 'Time_to_Review'],
      dtype='object')

In [72]:
df2=df2.drop(columns=['SOC_CODE','EMPLOYER_ADDRESS','EMPLOYER_CITY', \
    'EMPLOYER_STATE', \
    'EMPLOYER_COUNTRY',\
    'WORKSITE_CITY', 'WORKSITE_COUNTY','WORKSITE_STATE'])

In [73]:
X = df2.drop(columns=["CASE_STATUS"])
y = df2["CASE_STATUS"]

In [87]:
from sklearn.preprocessing import LabelEncoder

In [88]:
le =LabelEncoder()

In [89]:
df2["VISA_CLASS"]=le.fit_transform(df2["VISA_CLASS"])

In [93]:
df2

,CASE_STATUS,VISA_CLASS,EMPLOYMENT_START_DATE,EMPLOYMENT_END_DATE,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,...,PW_SOURCE,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE,Time_to_Review
0,CERTIFIED-WITHDRAWN,1,2016-08-10,2019-08-10,DISCOVER PRODUCTS INC.,60015,2244050900,Y,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,...,OES,2015.0,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,60015,220
1,CERTIFIED-WITHDRAWN,1,2016-08-16,2019-08-16,DFS SERVICES LLC,60015,2244050900,Y,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,...,Other,2015.0,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,60015,211
2,CERTIFIED-WITHDRAWN,1,2016-09-09,2019-09-09,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,...,OES,2015.0,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,20007,205
3,WITHDRAWN,1,2017-01-26,2020-01-25,INFO SERVICES LLC,48152,7343776007,N,",",PROJECT MANAGER,...,OES,2016.0,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,07302,3
4,CERTIFIED-WITHDRAWN,1,2015-03-01,2018-03-01,BB&T CORPORATION,27893,2522462031,Y,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,...,OES,2015.0,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,10036,588
5,CERTIFIED-WITHDRAWN,1,2015-09-11,2018-09-11,"SUNTRUST BANKS, INC.",30308,4048137888,Y,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,...,OES,2015.0,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,30303,570
6,CERTIFIED-WITHDRAWN,1,2016-08-25,2019-08-24,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",BUSINESS SYSTEMS ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,08837,220
7,CERTIFIED-WITHDRAWN,1,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,08837,220
8,CERTIFIED-WITHDRAWN,1,2016-08-26,2019-08-25,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,10005,218
9,CERTIFIED-WITHDRAWN,1,2016-08-29,2019-08-26,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",MARKET RESEARCH ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,08830,217
10,CERTIFIED-WITHDRAWN,1,2016-08-29,2019-08-29,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,10010,216
11,CERTIFIED-WITHDRAWN,1,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",BUSINESS ANALYST,...,Other,2015.0,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,08540,193
12,CERTIFIED-WITHDRAWN,1,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SAP BASIS ADMINISTRATOR,...,Other,2015.0,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,08901,193
13,CERTIFIED-WITHDRAWN,1,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,...,Other,2015.0,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,08901,193
14,CERTIFIED-WITHDRAWN,1,2016-09-22,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",ORACLE APPLICATION CONSULTANT,...,Other,2015.0,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,08901,193
15,CERTIFIED-WITHDRAWN,1,2016-09-23,2019-09-20,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,...,Other,2015.0,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,08901,192
16,WITHDRAWN,1,2016-10-08,2019-10-07,ITAS INC,46240,3175758950,Y,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,...,OES,2016.0,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,11747,0
17,CERTIFIED-WITHDRAWN,1,2013-12-02,2016-12-01,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,...,Other,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,99354,1112
18,CERTIFIED-WITHDRAWN,1,2013-10-14,2016-10-13,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,",",SCIENCE TEACHER,...,OES,2013.0,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,77099,1111
19,CERTIFIED-WITHDRAWN,1,2013-10-25,2016-10-24,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,",",FOREIGN LANGUAGE TEACHER,...,OES,2013.0,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,76710,1111
20,CERTIFIED-WITHDRAWN,1,2013-11-28,2016-11-27,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,"HO, WAI CHI",PROGRAMMER ANALYST,...,Other,2013.0,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,95035,1106
21,CERTIFIED-WITHDRAWN,1,2013-12-02,2016-12-01,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,...,Other,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,99354,1081
22,CERTIFIED-WITHDRAWN,1,2014-03-01,2017-02-28,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,",",POSTDOCTORAL RESEARCHER,...,OES,2013.0,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,97239,1078
23,CERTIFIED-WITHDRAWN,1,2013-11-23,2016-11-22,GIMMAL LLC,77046,7135866500,Y,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,...,Other,2013.0,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,77046,1075
24,CERTIFIED-WITHDRAWN,1,2014-01-01,2016-12-31,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,",",SCIENCE TEACHER,...,OES,2013.0,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,76040,1034
25,CERTIFIED-WITHDRAWN,1,2013-12-27,2016-12-26,"PLANTRONICS, INC.",95060,8314584458,Y,"DUONG, DAVID",SOFTWARE ENGINEER,...,OES,2013.0,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,78704,1015
26,CERTIFIED-WITHDRAWN,1,2014-05-11,2017-05-10,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,",",POSTDOCTORAL SCHOLAR,...,OES,2013.0,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,60637,1015
27,CERTIFIED-WITHDRAWN,1,2014-04-15,2017-04-14,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,",",POSTDOCTORAL SCHOLAR,...,CBA,2014.0,0,47244.00,0.0,Year,N,N,90095,952
28,CERTIFIED-WITHDRAWN,1,2014-08-24,2017-08-23,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,...,OES,2013.0,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,45236,950
29,CERTIFIED-WITHDRAWN,1,2014-06-07,2017-06-06,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,",",POSTDOCTORAL RESEARCH ASSOCIATE,...,OES,2013.0,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,99164,949
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,DENIED,0,2017-11-01,2019-11-01,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,",",ANALYST,...,OES,2017.0,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,0,0,10019,1
624621,WITHDRAWN,1,2017-12-19,2020-12-18,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,",",STORAGE (SAN) ADMINISTRATOR,...,OES,2017.0,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,76117,1
624622,WITHDRAWN,1,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,...,OES,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0
624623,WITHDRAWN,1,2017-10-09,2019-11-07,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SYSTEMS ANALYST,...,OES,2017.0,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,60007,0
624624,WITHDRAWN,1,2017-09-29,2018-05-01,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,",",COMPUTER SYSTEMS ANALYST,...,Other,2017.0,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,49423,0
624625,WITHDRAWN,1,2017-10-02,2020-10-01,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,...,OES,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0
624626,WITHDRAWN,1,2017-12-09,2020-12-08,PHILIPS NORTH AMERICA LLC,01810,0,0,",",SOFTWARE ENGINEER,...,OES,2017.0,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,94588-3050,0
624627,WITHDRAWN,1,2017-10-06,2020-10-05,"AMPCUS, INC.",20151,0,0,",",BUSINESS DATA ANALYST,...,OES,2017.0,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,20190,0
624628,WITHDRAWN,1,2017-10-10,2020-10-09,VIGILANT TECHNOLOGIES LLC,48084,0,0,",",ORACLE APPLICATION ENGINEER (OBIEE),...,OES,2016.0,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,48084,0
624629,WITHDRAWN,1,2017-10-16,2020-10-15,"ZUORA, INC.",94403,0,0,",",REVENUE ANALYST,...,OES,2017.0,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,95134,0
624630,WITHDRAWN,1,2017-12-18,2018-12-17,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,",",STAFF SCIENTIST,...,OES,2017.0,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,63110,0
624631,WITHDRAWN,1,2017-09-29,2020-09-28,"ARTEMIS CONSULTING, INC.",22181,0,0,",",APPLICATION DEVELOPER,...,OES,2017.0,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,20002,0
624632,WITHDRAWN,1,2017-10-11,2020-10-11,BANK OF AMERICA N.A.,10020,0,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,...,OES,2017.0,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,10036,0
624633,WITHDRAWN,1,2017-10-11,2020-08-16,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,...,Other,2017.0,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,77032,0
624634,WITHDRAWN,1,2017-10-30,2020-10-29,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,",",SENIOR FINANCIAL ACCOUNTANT,...,Other,2017.0,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,94088,0
624635,WITHDRAWN,1,2017-10-09,2020-10-08,CONSUMERINFO.COM,92626,0,0,",",SOFTWARE DEVELOPER EXPERT,...,Other,2017.0,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,92626,0
624636,WITHDRAWN,1,2017-12-13,2019-12-12,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,",",PROJECT ARCHITECT,...,OES,2017.0,0,87000.00,0.0,Year,N,N,90027,0
624637,WITHDRAWN,1,2017-10-06,2020-10-05,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,",",DESIGN ENGINEER,...,OES,2017.0,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,90245,0
624638,WITHDRAWN,1,2017-10-04,2020-10-03,"HCL AMERICA, INC.",94085,0,0,",",PROJECT MANAGER - III,...,OES,2017.0,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,55112,0
624639,WITHDRAWN,1,2017-09-29,2020-09-28,TECHNOSOFT GROUP INC,75062,0,0,",",SOFTWARE ENGINEER,...,OES,2017.0,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,55121,0
624640,WITHDRAWN,1,2017-10-09,2020-10-09,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SOFTWARE ENGINEER,...,OES,2017.0,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,02472,0
624641,WITHDRAWN,1,2017-10-06,2020-10-05,"CASA SYSTEMS, INC.",01810,0,0,",",TECHNICAL SUPPORT ENGINEER,...,Other,2017.0,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,01810,0
624642,CERTIFIED-WITHDRAWN,1,2015-10-02,2018-10-01,"STLPORT CONSULTING, INC.",94043,0,0,",",GRAPHIC DESIGNER,...,Other,2014.0,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,94043,880
624643,CERTIFIED-WITHDRAWN,1,2015-08-01,2018-07-31,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,...,Other,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,792
624644,CERTIFIED-WITHDRAWN,1,2015-08-11,2018-07-31,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,...,Other,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,781
624645,CERTIFIED-WITHDRAWN,1,2016-07-06,2019-07-05,FAST SWITCH LTD,43017,0,0,",",SENIOR JAVA DEVELOPER,...,OES,2016.0,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,43017,451
624646,CERTIFIED,1,2016-12-01,2017-11-30,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,...,OES,2016.0,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,02139,6
624647,CERTIFIED,1,2017-02-01,2018-01-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",RESEARCH SCIENTIST,...,OES,2016.0,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,02139,7
624648,CERTIFIED,1,2017-06-01,2018-05-31,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,...,OES,2016.0,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,02139,6
624649,CERTIFIED,1,2017-09-08,2020-09-08,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,...,OES,2016.0,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,90210,6

In [94]:
df2["EMPLOYMENT_END_DATE"]=pd.to_datetime(df2["EMPLOYMENT_END_DATE"])
df2["EMPLOYMENT_START_DATE"]=pd.to_datetime(df2["EMPLOYMENT_START_DATE"])

df2['Emp_Time'] = (df2['EMPLOYMENT_END_DATE']-df2['EMPLOYMENT_START_DATE']).dt.days

In [95]:
df2= df2.drop(columns=["EMPLOYMENT_START_DATE","EMPLOYMENT_START_DATE"])

In [103]:
df2= df2.drop(columns=["EMPLOYMENT_END_DATE"])

In [105]:
df2.dtypes

CASE_STATUS                     object
VISA_CLASS                       int64
EMPLOYER_NAME                   object
EMPLOYER_POSTAL_CODE            object
EMPLOYER_PHONE                  object
AGENT_REPRESENTING_EMPLOYER     object
AGENT_ATTORNEY_NAME             object
JOB_TITLE                       object
SOC_NAME                        object
NAICS_CODE                      object
TOTAL_WORKERS                    int64
NEW_EMPLOYMENT                   int64
CONTINUED_EMPLOYMENT             int64
CHANGE_PREVIOUS_EMPLOYMENT       int64
NEW_CONCURRENT_EMPLOYMENT        int64
CHANGE_EMPLOYER                  int64
AMENDED_PETITION                 int64
FULL_TIME_POSITION              object
PREVAILING_WAGE                float64
PW_UNIT_OF_PAY                  object
PW_WAGE_LEVEL                   object
PW_SOURCE                       object
PW_SOURCE_YEAR                 float64
PW_SOURCE_OTHER                 object
WAGE_RATE_OF_PAY_FROM          float64
WAGE_RATE_OF_PAY_TO            float64
WAGE_UNIT_OF_PAY                object
H1B_DEPENDENT                   object
WILLFUL_VIOLATOR                object
WORKSITE_POSTAL_CODE            object
Time_to_Review                   int64
Emp_Time                         int64
dtype: object

In [108]:
df2["Time_to_Review"]=df2["Time_to_Review"].astype(float)

In [109]:
df2["Emp_Time"]=df2["Emp_Time"].astype(float)

In [115]:
X = df2.drop(columns=["CASE_STATUS"])
y = df2["CASE_STATUS"]

In [118]:
X.dtypes

VISA_CLASS                       int64
EMPLOYER_NAME                   object
EMPLOYER_POSTAL_CODE            object
EMPLOYER_PHONE                  object
AGENT_REPRESENTING_EMPLOYER     object
AGENT_ATTORNEY_NAME             object
JOB_TITLE                       object
SOC_NAME                        object
NAICS_CODE                      object
TOTAL_WORKERS                    int64
NEW_EMPLOYMENT                   int64
CONTINUED_EMPLOYMENT             int64
CHANGE_PREVIOUS_EMPLOYMENT       int64
NEW_CONCURRENT_EMPLOYMENT        int64
CHANGE_EMPLOYER                  int64
AMENDED_PETITION                 int64
FULL_TIME_POSITION              object
PREVAILING_WAGE                float64
PW_UNIT_OF_PAY                  object
PW_WAGE_LEVEL                   object
PW_SOURCE                       object
PW_SOURCE_YEAR                 float64
PW_SOURCE_OTHER                 object
WAGE_RATE_OF_PAY_FROM          float64
WAGE_RATE_OF_PAY_TO            float64
WAGE_UNIT_OF_PAY                object
H1B_DEPENDENT                   object
WILLFUL_VIOLATOR                object
WORKSITE_POSTAL_CODE            object
Time_to_Review                 float64
Emp_Time                       float64
dtype: object

In [110]:
from sklearn.model_selection import train_test_split as tts
X_train, X_test, y_train, y_test = tts(X,y, test_size = 0.3, random_state= 42)

In [130]:
# DT=DecisionTreeClassifier(max_depth=15, min_samples_leaf=100)

# DT.fit(X_train,y_train)

In [139]:
df_with_dummies= pd.get_dummies(df2,columns=["AGENT_REPRESENTING_EMPLOYER","FULL_TIME_POSITION","H1B_DEPENDENT","WILLFUL_VIOLATOR"],drop_first=False)

In [142]:
df_with_dummies.select_dtypes(include=[object])

,CASE_STATUS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,PW_UNIT_OF_PAY,PW_WAGE_LEVEL,PW_SOURCE,PW_SOURCE_OTHER,WAGE_UNIT_OF_PAY,WORKSITE_POSTAL_CODE
0,CERTIFIED-WITHDRAWN,DISCOVER PRODUCTS INC.,60015,2244050900,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,60015
1,CERTIFIED-WITHDRAWN,DFS SERVICES LLC,60015,2244050900,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,Year,0,Other,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,Year,60015
2,CERTIFIED-WITHDRAWN,EASTBANC TECHNOLOGIES LLC,20007,2022953000,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,20007
3,WITHDRAWN,INFO SERVICES LLC,48152,7343776007,",",PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,07302
4,CERTIFIED-WITHDRAWN,BB&T CORPORATION,27893,2522462031,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,10036
5,CERTIFIED-WITHDRAWN,"SUNTRUST BANKS, INC.",30308,4048137888,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,30303
6,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,",",BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08837
7,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08837
8,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,10005
9,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,",",MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08830
10,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,10010
11,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,",",BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08540
12,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,",",SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08901
13,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08901
14,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,",",ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08901
15,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,08901
16,WITHDRAWN,ITAS INC,46240,3175758950,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,11747
17,CERTIFIED-WITHDRAWN,BATTELLE,99354,5093753959,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,Year,Level I,Other,FOREIGN LABOR CERTIFICATION DATA CENTER,Year,99354
18,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,77099
19,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,",",FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,76710
20,CERTIFIED-WITHDRAWN,"IDC TECHNOLOGIES, INC.",95035,4083830155,"HO, WAI CHI",PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Year,Level III,Other,OFLC ONLINE DATA CENTER,Year,95035
21,CERTIFIED-WITHDRAWN,BATTELLE,99354,5093753959,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,Hour,Level I,Other,FOREIGN LABOR CERTIFICATION DATA CENTER,Hour,99354
22,CERTIFIED-WITHDRAWN,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,",",POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,97239
23,CERTIFIED-WITHDRAWN,GIMMAL LLC,77046,7135866500,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,Year,Level II,Other,OFLC ONLINE DATA CENTER,Year,77046
24,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,76040
25,CERTIFIED-WITHDRAWN,"PLANTRONICS, INC.",95060,8314584458,"DUONG, DAVID",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,78704
26,CERTIFIED-WITHDRAWN,THE UNIVERSITY OF CHICAGO,60637,7737027752,",",POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,60637
27,CERTIFIED-WITHDRAWN,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,",",POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,Year,0,CBA,0,Year,90095
28,CERTIFIED-WITHDRAWN,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,45236
29,CERTIFIED-WITHDRAWN,WASHINGTON STATE UNIVERSITY,99164,5093354508,",",POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,99164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,DENIED,ELLIOTT MANAGEMENT CORPORATION,10019,0,",",ANALYST,FINANCIAL ANALYSTS,523110,Year,0,OES,OFLC ONLINE DATA CENTER,Year,10019
624621,WITHDRAWN,I NET SOFTWARE TECHNOLOGIES INC,75063,0,",",STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Hour,76117
624622,WITHDRAWN,"NTT DATA SERVICES, LLC",75075,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,75039
624623,WITHDRAWN,"FRONTIER TECHNOLOGIES, LLC",60563,0,",",SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,60007
624624,WITHDRAWN,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,",",COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Year,0,Other,OFLC ONLINE DATA CENTER,Year,49423
624625,WITHDRAWN,"NTT DATA SERVICES, LLC",75075,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,75039
624626,WITHDRAWN,PHILIPS NORTH AMERICA LLC,01810,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,Year,0,OES,OFLC ONLINE DATA CENTER,Year,94588-3050
624627,WITHDRAWN,"AMPCUS, INC.",20151,0,",",BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,20190
624628,WITHDRAWN,VIGILANT TECHNOLOGIES LLC,48084,0,",",ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,48084
624629,WITHDRAWN,"ZUORA, INC.",94403,0,",",REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,95134
624630,WITHDRAWN,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,",",STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,Year,0,OES,OFLC ONLINE DATA CENTER,Year,63110
624631,WITHDRAWN,"ARTEMIS CONSULTING, INC.",22181,0,",",APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,20002
624632,WITHDRAWN,BANK OF AMERICA N.A.,10020,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,Year,0,OES,OFLC ONLINE DATA CENTER,Year,10036
624633,WITHDRAWN,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,Year,0,Other,DIETRICH 2017 ENGINEERING SALARY SURVEY,Year,77032
624634,WITHDRAWN,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,",",SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,Year,0,Other,RADFORD GLOBAL TECHNOLOGY SURVEY,Year,94088
624635,WITHDRAWN,CONSUMERINFO.COM,92626,0,",",SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,Year,0,Other,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,Year,92626
624636,WITHDRAWN,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,",",PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,Year,0,OES,0,Year,90027
624637,WITHDRAWN,L&T TECHNOLOGY SERVICES LIMITED,08817,0,",",DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,Year,0,OES,OFLC ONLINE DATA CENTER,Year,90245
624638,WITHDRAWN,"HCL AMERICA, INC.",94085,0,",",PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,55112
624639,WITHDRAWN,TECHNOSOFT GROUP INC,75062,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,55121
624640,WITHDRAWN,"FRONTIER TECHNOLOGIES, LLC",60563,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Year,0,OES,OFLC ONLINE DATA CENTER,Year,02472
624641,WITHDRAWN,"CASA SYSTEMS, INC.",01810,0,",",TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,Year,0,Other,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,Year,01810
624642,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,",",GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,Hour,0,Other,FLC ONLINE WAGE LIBRARY,Hour,94043
624643,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,Hour,0,Other,OFLC ONLINE DATA CENTER,Hour,94043
624644,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,Hour,0,Other,OFLC ONLINE DATA CENTER,Hour,94043
624645,CERTIFIED-WITHDRAWN,FAST SWITCH LTD,43017,0,",",SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Hour,0,OES,OFLC ONLINE DATA CENTER,Hour,43017
624646,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,",",POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,02139
624647,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,",",RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,02139
624648,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,",",POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,02139
624649,CERTIFIED,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,90210

In [137]:
df2.select_dtypes(include=[object])

,CASE_STATUS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,FULL_TIME_POSITION,PW_UNIT_OF_PAY,PW_WAGE_LEVEL,PW_SOURCE,PW_SOURCE_OTHER,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE
0,CERTIFIED-WITHDRAWN,DISCOVER PRODUCTS INC.,60015,2244050900,Y,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,60015
1,CERTIFIED-WITHDRAWN,DFS SERVICES LLC,60015,2244050900,Y,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,Y,Year,0,Other,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,Year,N,N,60015
2,CERTIFIED-WITHDRAWN,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,Y,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,Y,N,20007
3,WITHDRAWN,INFO SERVICES LLC,48152,7343776007,N,",",PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,Y,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,Y,N,07302
4,CERTIFIED-WITHDRAWN,BB&T CORPORATION,27893,2522462031,Y,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,Y,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,N,N,10036
5,CERTIFIED-WITHDRAWN,"SUNTRUST BANKS, INC.",30308,4048137888,Y,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,Y,Year,Level III,OES,OFLC ONLINE DATA CENTER,Year,N,N,30303
6,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08837
7,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08837
8,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,10005
9,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08830
10,CERTIFIED-WITHDRAWN,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,10010
11,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08540
12,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08901
13,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08901
14,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08901
15,CERTIFIED-WITHDRAWN,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,Level I,Other,ONLINE WAGE LIBRARY,Year,Y,N,08901
16,WITHDRAWN,ITAS INC,46240,3175758950,Y,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,11747
17,CERTIFIED-WITHDRAWN,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,Y,Year,Level I,Other,FOREIGN LABOR CERTIFICATION DATA CENTER,Year,N,N,99354
18,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,77099
19,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,",",FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,76710
20,CERTIFIED-WITHDRAWN,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,"HO, WAI CHI",PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,Level III,Other,OFLC ONLINE DATA CENTER,Year,Y,N,95035
21,CERTIFIED-WITHDRAWN,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,N,Hour,Level I,Other,FOREIGN LABOR CERTIFICATION DATA CENTER,Hour,N,N,99354
22,CERTIFIED-WITHDRAWN,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,",",POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,97239
23,CERTIFIED-WITHDRAWN,GIMMAL LLC,77046,7135866500,Y,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,Y,Year,Level II,Other,OFLC ONLINE DATA CENTER,Year,N,N,77046
24,CERTIFIED-WITHDRAWN,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,76040
25,CERTIFIED-WITHDRAWN,"PLANTRONICS, INC.",95060,8314584458,Y,"DUONG, DAVID",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,78704
26,CERTIFIED-WITHDRAWN,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,",",POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,60637
27,CERTIFIED-WITHDRAWN,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,",",POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,Y,Year,0,CBA,0,Year,N,N,90095
28,CERTIFIED-WITHDRAWN,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,45236
29,CERTIFIED-WITHDRAWN,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,",",POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,99164
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,DENIED,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,",",ANALYST,FINANCIAL ANALYSTS,523110,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,0,0,10019
624621,WITHDRAWN,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,",",STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Hour,Y,N,76117
624622,WITHDRAWN,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,75039
624623,WITHDRAWN,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,60007
624624,WITHDRAWN,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,",",COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,0,Other,OFLC ONLINE DATA CENTER,Year,Y,N,49423
624625,WITHDRAWN,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,75039
624626,WITHDRAWN,PHILIPS NORTH AMERICA LLC,01810,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,94588-3050
624627,WITHDRAWN,"AMPCUS, INC.",20151,0,0,",",BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,20190
624628,WITHDRAWN,VIGILANT TECHNOLOGIES LLC,48084,0,0,",",ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,48084
624629,WITHDRAWN,"ZUORA, INC.",94403,0,0,",",REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,95134
624630,WITHDRAWN,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,",",STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,63110
624631,WITHDRAWN,"ARTEMIS CONSULTING, INC.",22181,0,0,",",APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,20002
624632,WITHDRAWN,BANK OF AMERICA N.A.,10020,0,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,N,N,10036
624633,WITHDRAWN,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,Y,Year,0,Other,DIETRICH 2017 ENGINEERING SALARY SURVEY,Year,N,N,77032
624634,WITHDRAWN,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,",",SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,Y,Year,0,Other,RADFORD GLOBAL TECHNOLOGY SURVEY,Year,N,N,94088
624635,WITHDRAWN,CONSUMERINFO.COM,92626,0,0,",",SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,Y,Year,0,Other,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,Year,N,N,92626
624636,WITHDRAWN,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,",",PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,Y,Year,0,OES,0,Year,N,N,90027
624637,WITHDRAWN,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,",",DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,90245
624638,WITHDRAWN,"HCL AMERICA, INC.",94085,0,0,",",PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,55112
624639,WITHDRAWN,TECHNOSOFT GROUP INC,75062,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,55121
624640,WITHDRAWN,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Year,0,OES,OFLC ONLINE DATA CENTER,Year,Y,N,02472
624641,WITHDRAWN,"CASA SYSTEMS, INC.",01810,0,0,",",TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,Y,Year,0,Other,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,Year,N,N,01810
624642,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,0,",",GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,N,Hour,0,Other,FLC ONLINE WAGE LIBRARY,Hour,N,N,94043
624643,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,N,Hour,0,Other,OFLC ONLINE DATA CENTER,Hour,N,N,94043
624644,CERTIFIED-WITHDRAWN,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,N,Hour,0,Other,OFLC ONLINE DATA CENTER,Hour,N,N,94043
624645,CERTIFIED-WITHDRAWN,FAST SWITCH LTD,43017,0,0,",",SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,Y,Hour,0,OES,OFLC ONLINE DATA CENTER,Hour,Y,N,43017
624646,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,02139
624647,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,Y,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,N,N,02139
624648,CERTIFIED,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,Y,Year,Level I,OES,OFLC ONLINE DATA CENTER,Year,N,N,02139
624649,CERTIFIED,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,Y,Year,Level II,OES,OFLC ONLINE DATA CENTER,Year,N,N,90210

In [138]:
df2.select_dtypes(exclude=[object])

,VISA_CLASS,TOTAL_WORKERS,NEW_EMPLOYMENT,CONTINUED_EMPLOYMENT,CHANGE_PREVIOUS_EMPLOYMENT,NEW_CONCURRENT_EMPLOYMENT,CHANGE_EMPLOYER,AMENDED_PETITION,PREVAILING_WAGE,PW_SOURCE_YEAR,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,Time_to_Review,Emp_Time
0,1,1,1,0,0,0,0,0,59197.00,2015.0,65811.00,67320.0,220.0,1095.0
1,1,1,1,0,0,0,0,0,49800.00,2015.0,53000.00,57200.0,211.0,1095.0
2,1,2,2,0,0,0,0,0,76502.00,2015.0,77000.00,0.0,205.0,1095.0
3,1,1,1,0,0,0,0,0,90376.00,2016.0,102000.00,0.0,3.0,1094.0
4,1,1,0,0,0,0,1,0,116605.00,2015.0,132500.00,0.0,588.0,1096.0
5,1,1,1,0,0,0,0,0,59405.00,2015.0,71750.00,0.0,570.0,1096.0
6,1,1,1,0,0,0,0,0,52915.00,2015.0,61000.00,0.0,220.0,1094.0
7,1,1,1,0,0,0,0,0,51730.00,2015.0,60500.00,0.0,220.0,1094.0
8,1,1,1,0,0,0,0,0,58053.00,2015.0,60450.00,0.0,218.0,1094.0
9,1,1,1,0,0,0,0,0,46821.00,2015.0,50000.00,0.0,217.0,1092.0
10,1,1,1,0,0,0,0,0,58053.00,2015.0,60400.00,0.0,216.0,1095.0
11,1,1,1,0,0,0,0,0,63170.00,2015.0,63200.00,0.0,193.0,1093.0
12,1,1,1,0,0,0,0,0,51730.00,2015.0,60100.00,0.0,193.0,1093.0
13,1,1,1,0,0,0,0,0,63877.00,2015.0,64000.00,0.0,193.0,1093.0
14,1,1,1,0,0,0,0,0,51730.00,2015.0,60000.00,0.0,193.0,1093.0
15,1,1,1,0,0,0,0,0,63877.00,2015.0,65000.00,0.0,192.0,1092.0
16,1,1,0,0,0,0,1,0,54600.00,2016.0,55000.00,0.0,0.0,1094.0
17,1,1,1,0,0,0,0,0,39853.00,2013.0,60000.00,0.0,1112.0,1095.0
18,1,1,0,1,0,0,0,0,43110.00,2013.0,43110.00,0.0,1111.0,1095.0
19,1,1,0,1,0,0,0,0,38970.00,2013.0,38970.00,0.0,1111.0,1095.0
20,1,1,0,1,0,0,0,0,96845.00,2013.0,104000.00,0.0,1106.0,1095.0
21,1,1,1,0,0,0,0,0,19.16,2013.0,28.85,0.0,1081.0,1095.0
22,1,1,1,0,0,0,0,0,40706.00,2013.0,40706.00,0.0,1078.0,1095.0
23,1,1,0,1,0,0,0,0,77875.00,2013.0,78000.00,0.0,1075.0,1095.0
24,1,1,0,1,0,0,0,0,45540.00,2013.0,45540.00,0.0,1034.0,1095.0
25,1,1,1,0,0,0,0,0,66331.00,2013.0,66331.00,95000.0,1015.0,1095.0
26,1,1,1,0,0,0,0,0,37440.00,2013.0,39611.00,0.0,1015.0,1095.0
27,1,1,1,0,0,0,0,0,47244.00,2014.0,47244.00,0.0,952.0,1095.0
28,1,1,1,0,0,0,0,0,46696.00,2013.0,70000.00,0.0,950.0,1095.0
29,1,1,0,1,0,0,0,0,35734.00,2013.0,41600.00,0.0,949.0,1095.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,0,1,0,1,0,0,1,0,101254.00,2017.0,125000.00,0.0,1.0,730.0
624621,1,1,0,0,1,0,0,0,93683.00,2017.0,55.00,65.0,1.0,1095.0
624622,1,1,0,0,0,0,0,1,112528.00,2017.0,112528.00,142528.0,0.0,1095.0
624623,1,1,0,0,0,0,0,1,75046.00,2017.0,75100.00,0.0,0.0,759.0
624624,1,1,0,0,0,0,0,1,71594.00,2017.0,82000.00,0.0,0.0,214.0
624625,1,1,0,0,0,0,0,1,112528.00,2017.0,112528.00,142528.0,0.0,1095.0
624626,1,1,0,1,0,0,0,0,131165.00,2017.0,145285.00,0.0,0.0,1095.0
624627,1,1,0,0,1,0,0,1,102731.00,2017.0,102731.00,0.0,0.0,1095.0
624628,1,1,0,0,0,0,0,1,71635.00,2016.0,72000.00,0.0,0.0,1095.0
624629,1,1,0,0,0,0,1,0,101067.00,2017.0,110000.00,0.0,0.0,1095.0
624630,1,1,0,1,0,0,0,0,47861.00,2017.0,47476.00,0.0,0.0,364.0
624631,1,1,0,0,0,0,1,0,92019.00,2017.0,105000.00,0.0,0.0,1095.0
624632,1,1,0,0,0,0,0,1,85155.00,2017.0,98000.00,0.0,0.0,1096.0
624633,1,1,0,0,1,0,0,0,85424.00,2017.0,88500.00,0.0,0.0,1040.0
624634,1,1,0,0,0,0,1,0,90377.00,2017.0,90377.00,122600.0,0.0,1095.0
624635,1,1,0,0,0,0,1,0,113700.00,2017.0,128000.00,0.0,0.0,1095.0
624636,1,1,0,1,0,0,0,0,75421.00,2017.0,87000.00,0.0,0.0,729.0
624637,1,1,0,0,0,0,0,1,58427.00,2017.0,64000.00,74000.0,0.0,1095.0
624638,1,20,5,5,0,0,5,5,88462.00,2017.0,88462.00,0.0,0.0,1095.0
624639,1,1,0,0,0,0,0,1,78624.00,2017.0,78700.00,0.0,0.0,1095.0
624640,1,1,0,0,0,0,0,1,87859.00,2017.0,87864.00,0.0,0.0,1096.0
624641,1,1,0,0,0,0,1,0,64016.00,2017.0,67000.00,70000.0,0.0,1095.0
624642,1,1,0,1,0,0,0,0,24.01,2014.0,28.50,0.0,880.0,1095.0
624643,1,1,1,0,0,0,0,0,57.86,2015.0,57.86,0.0,792.0,1095.0
624644,1,1,0,0,0,1,0,0,57.86,2015.0,57.86,0.0,781.0,1085.0
624645,1,1,0,1,0,0,0,0,37.12,2016.0,46.00,0.0,451.0,1094.0
624646,1,1,0,1,0,0,0,0,50398.00,2016.0,60400.00,0.0,6.0,364.0
624647,1,1,1,0,0,0,0,0,61069.00,2016.0,65000.00,0.0,7.0,364.0
624648,1,1,0,1,0,0,0,0,41392.00,2016.0,49383.00,0.0,6.0,364.0
624649,1,1,1,0,0,0,0,0,45198.00,2016.0,45200.00,0.0,6.0,1096.0

In [143]:
df2

,CASE_STATUS,VISA_CLASS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,...,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE,Time_to_Review,Emp_Time
0,CERTIFIED-WITHDRAWN,1,DISCOVER PRODUCTS INC.,60015,2244050900,Y,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,...,2015.0,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,60015,220.0,1095.0
1,CERTIFIED-WITHDRAWN,1,DFS SERVICES LLC,60015,2244050900,Y,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,...,2015.0,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,60015,211.0,1095.0
2,CERTIFIED-WITHDRAWN,1,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,...,2015.0,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,20007,205.0,1095.0
3,WITHDRAWN,1,INFO SERVICES LLC,48152,7343776007,N,",",PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,...,2016.0,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,07302,3.0,1094.0
4,CERTIFIED-WITHDRAWN,1,BB&T CORPORATION,27893,2522462031,Y,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,...,2015.0,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,10036,588.0,1096.0
5,CERTIFIED-WITHDRAWN,1,"SUNTRUST BANKS, INC.",30308,4048137888,Y,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,...,2015.0,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,30303,570.0,1096.0
6,CERTIFIED-WITHDRAWN,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,...,2015.0,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,08837,220.0,1094.0
7,CERTIFIED-WITHDRAWN,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,08837,220.0,1094.0
8,CERTIFIED-WITHDRAWN,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,10005,218.0,1094.0
9,CERTIFIED-WITHDRAWN,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,...,2015.0,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,08830,217.0,1092.0
10,CERTIFIED-WITHDRAWN,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,10010,216.0,1095.0
11,CERTIFIED-WITHDRAWN,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,08540,193.0,1093.0
12,CERTIFIED-WITHDRAWN,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,08901,193.0,1093.0
13,CERTIFIED-WITHDRAWN,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2015.0,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,08901,193.0,1093.0
14,CERTIFIED-WITHDRAWN,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,...,2015.0,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,08901,193.0,1093.0
15,CERTIFIED-WITHDRAWN,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2015.0,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,08901,192.0,1092.0
16,WITHDRAWN,1,ITAS INC,46240,3175758950,Y,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,...,2016.0,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,11747,0.0,1094.0
17,CERTIFIED-WITHDRAWN,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,99354,1112.0,1095.0
18,CERTIFIED-WITHDRAWN,1,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,...,2013.0,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,77099,1111.0,1095.0
19,CERTIFIED-WITHDRAWN,1,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,",",FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,...,2013.0,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,76710,1111.0,1095.0
20,CERTIFIED-WITHDRAWN,1,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,"HO, WAI CHI",PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,...,2013.0,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,95035,1106.0,1095.0
21,CERTIFIED-WITHDRAWN,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,99354,1081.0,1095.0
22,CERTIFIED-WITHDRAWN,1,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,",",POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,...,2013.0,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,97239,1078.0,1095.0
23,CERTIFIED-WITHDRAWN,1,GIMMAL LLC,77046,7135866500,Y,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,...,2013.0,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,77046,1075.0,1095.0
24,CERTIFIED-WITHDRAWN,1,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,...,2013.0,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,76040,1034.0,1095.0
25,CERTIFIED-WITHDRAWN,1,"PLANTRONICS, INC.",95060,8314584458,Y,"DUONG, DAVID",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,...,2013.0,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,78704,1015.0,1095.0
26,CERTIFIED-WITHDRAWN,1,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,",",POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,...,2013.0,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,60637,1015.0,1095.0
27,CERTIFIED-WITHDRAWN,1,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,",",POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,...,2014.0,0,47244.00,0.0,Year,N,N,90095,952.0,1095.0
28,CERTIFIED-WITHDRAWN,1,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,...,2013.0,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,45236,950.0,1095.0
29,CERTIFIED-WITHDRAWN,1,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,",",POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,...,2013.0,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,99164,949.0,1095.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,DENIED,0,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,",",ANALYST,FINANCIAL ANALYSTS,523110,...,2017.0,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,0,0,10019,1.0,730.0
624621,WITHDRAWN,1,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,",",STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,...,2017.0,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,76117,1.0,1095.0
624622,WITHDRAWN,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624623,WITHDRAWN,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,...,2017.0,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,60007,0.0,759.0
624624,WITHDRAWN,1,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,",",COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,...,2017.0,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,49423,0.0,214.0
624625,WITHDRAWN,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624626,WITHDRAWN,1,PHILIPS NORTH AMERICA LLC,01810,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,...,2017.0,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,94588-3050,0.0,1095.0
624627,WITHDRAWN,1,"AMPCUS, INC.",20151,0,0,",",BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,...,2017.0,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,20190,0.0,1095.0
624628,WITHDRAWN,1,VIGILANT TECHNOLOGIES LLC,48084,0,0,",",ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2016.0,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,48084,0.0,1095.0
624629,WITHDRAWN,1,"ZUORA, INC.",94403,0,0,",",REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,...,2017.0,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,95134,0.0,1095.0
624630,WITHDRAWN,1,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,",",STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,...,2017.0,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,63110,0.0,364.0
624631,WITHDRAWN,1,"ARTEMIS CONSULTING, INC.",22181,0,0,",",APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2017.0,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,20002,0.0,1095.0
624632,WITHDRAWN,1,BANK OF AMERICA N.A.,10020,0,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,...,2017.0,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,10036,0.0,1096.0
624633,WITHDRAWN,1,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,...,2017.0,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,77032,0.0,1040.0
624634,WITHDRAWN,1,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,",",SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,...,2017.0,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,94088,0.0,1095.0
624635,WITHDRAWN,1,CONSUMERINFO.COM,92626,0,0,",",SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,...,2017.0,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,92626,0.0,1095.0
624636,WITHDRAWN,1,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,",",PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,...,2017.0,0,87000.00,0.0,Year,N,N,90027,0.0,729.0
624637,WITHDRAWN,1,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,",",DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,...,2017.0,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,90245,0.0,1095.0
624638,WITHDRAWN,1,"HCL AMERICA, INC.",94085,0,0,",",PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,...,2017.0,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,55112,0.0,1095.0
624639,WITHDRAWN,1,TECHNOSOFT GROUP INC,75062,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2017.0,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,55121,0.0,1095.0
624640,WITHDRAWN,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2017.0,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,02472,0.0,1096.0
624641,WITHDRAWN,1,"CASA SYSTEMS, INC.",01810,0,0,",",TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,...,2017.0,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,01810,0.0,1095.0
624642,CERTIFIED-WITHDRAWN,1,"STLPORT CONSULTING, INC.",94043,0,0,",",GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,...,2014.0,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,94043,880.0,1095.0
624643,CERTIFIED-WITHDRAWN,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,792.0,1095.0
624644,CERTIFIED-WITHDRAWN,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,781.0,1085.0
624645,CERTIFIED-WITHDRAWN,1,FAST SWITCH LTD,43017,0,0,",",SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,...,2016.0,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,43017,451.0,1094.0
624646,CERTIFIED,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,...,2016.0,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,02139,6.0,364.0
624647,CERTIFIED,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,...,2016.0,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,02139,7.0,364.0
624648,CERTIFIED,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,...,2016.0,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,02139,6.0,364.0
624649,CERTIFIED,1,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,...,2016.0,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,90210,6.0,1096.0

In [144]:
X

,VISA_CLASS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,TOTAL_WORKERS,...,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE,Time_to_Review,Emp_Time
0,1,DISCOVER PRODUCTS INC.,60015,2244050900,Y,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,1,...,2015.0,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,60015,220.0,1095.0
1,1,DFS SERVICES LLC,60015,2244050900,Y,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,1,...,2015.0,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,60015,211.0,1095.0
2,1,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,2,...,2015.0,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,20007,205.0,1095.0
3,1,INFO SERVICES LLC,48152,7343776007,N,",",PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,07302,3.0,1094.0
4,1,BB&T CORPORATION,27893,2522462031,Y,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,1,...,2015.0,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,10036,588.0,1096.0
5,1,"SUNTRUST BANKS, INC.",30308,4048137888,Y,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,1,...,2015.0,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,30303,570.0,1096.0
6,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,08837,220.0,1094.0
7,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,08837,220.0,1094.0
8,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,10005,218.0,1094.0
9,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,1,...,2015.0,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,08830,217.0,1092.0
10,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,10010,216.0,1095.0
11,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,08540,193.0,1093.0
12,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,08901,193.0,1093.0
13,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,08901,193.0,1093.0
14,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,08901,193.0,1093.0
15,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,08901,192.0,1092.0
16,1,ITAS INC,46240,3175758950,Y,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,1,...,2016.0,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,11747,0.0,1094.0
17,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,99354,1112.0,1095.0
18,1,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,77099,1111.0,1095.0
19,1,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,",",FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,76710,1111.0,1095.0
20,1,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,"HO, WAI CHI",PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2013.0,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,95035,1106.0,1095.0
21,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,99354,1081.0,1095.0
22,1,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,",",POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,1,...,2013.0,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,97239,1078.0,1095.0
23,1,GIMMAL LLC,77046,7135866500,Y,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,1,...,2013.0,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,77046,1075.0,1095.0
24,1,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,76040,1034.0,1095.0
25,1,"PLANTRONICS, INC.",95060,8314584458,Y,"DUONG, DAVID",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,1,...,2013.0,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,78704,1015.0,1095.0
26,1,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,",",POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,60637,1015.0,1095.0
27,1,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,",",POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2014.0,0,47244.00,0.0,Year,N,N,90095,952.0,1095.0
28,1,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,1,...,2013.0,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,45236,950.0,1095.0
29,1,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,",",POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,99164,949.0,1095.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,0,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,",",ANALYST,FINANCIAL ANALYSTS,523110,1,...,2017.0,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,0,0,10019,1.0,730.0
624621,1,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,",",STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,76117,1.0,1095.0
624622,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624623,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,60007,0.0,759.0
624624,1,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,",",COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,49423,0.0,214.0
624625,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624626,1,PHILIPS NORTH AMERICA LLC,01810,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,1,...,2017.0,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,94588-3050,0.0,1095.0
624627,1,"AMPCUS, INC.",20151,0,0,",",BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,20190,0.0,1095.0
624628,1,VIGILANT TECHNOLOGIES LLC,48084,0,0,",",ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,48084,0.0,1095.0
624629,1,"ZUORA, INC.",94403,0,0,",",REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,95134,0.0,1095.0
624630,1,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,",",STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2017.0,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,63110,0.0,364.0
624631,1,"ARTEMIS CONSULTING, INC.",22181,0,0,",",APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,20002,0.0,1095.0
624632,1,BANK OF AMERICA N.A.,10020,0,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,1,...,2017.0,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,10036,0.0,1096.0
624633,1,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,1,...,2017.0,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,77032,0.0,1040.0
624634,1,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,",",SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,1,...,2017.0,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,94088,0.0,1095.0
624635,1,CONSUMERINFO.COM,92626,0,0,",",SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,1,...,2017.0,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,92626,0.0,1095.0
624636,1,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,",",PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,1,...,2017.0,0,87000.00,0.0,Year,N,N,90027,0.0,729.0
624637,1,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,",",DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,1,...,2017.0,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,90245,0.0,1095.0
624638,1,"HCL AMERICA, INC.",94085,0,0,",",PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,20,...,2017.0,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,55112,0.0,1095.0
624639,1,TECHNOSOFT GROUP INC,75062,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,55121,0.0,1095.0
624640,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,02472,0.0,1096.0
624641,1,"CASA SYSTEMS, INC.",01810,0,0,",",TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,1,...,2017.0,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,01810,0.0,1095.0
624642,1,"STLPORT CONSULTING, INC.",94043,0,0,",",GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,1,...,2014.0,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,94043,880.0,1095.0
624643,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,792.0,1095.0
624644,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,781.0,1085.0
624645,1,FAST SWITCH LTD,43017,0,0,",",SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,43017,451.0,1094.0
624646,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,02139,6.0,364.0
624647,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,1,...,2016.0,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,02139,7.0,364.0
624648,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,02139,6.0,364.0
624649,1,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,1,...,2016.0,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,90210,6.0,1096.0

In [145]:
obj_col = X.columns[X.dtypes == 'object']

In [146]:
obj_col

Index(['EMPLOYER_NAME', 'EMPLOYER_POSTAL_CODE', 'EMPLOYER_PHONE',
       'AGENT_REPRESENTING_EMPLOYER', 'AGENT_ATTORNEY_NAME', 'JOB_TITLE',
       'SOC_NAME', 'NAICS_CODE', 'FULL_TIME_POSITION', 'PW_UNIT_OF_PAY',
       'PW_WAGE_LEVEL', 'PW_SOURCE', 'PW_SOURCE_OTHER', 'WAGE_UNIT_OF_PAY',
       'H1B_DEPENDENT', 'WILLFUL_VIOLATOR', 'WORKSITE_POSTAL_CODE'],
      dtype='object')

In [150]:
# for i in obj_col:
#     try:
#         X[i] = le.fit_transform(X[i])
#         print(i)
#     except:
#         print('not categorical')

In [162]:
X = df2.drop(columns=["CASE_STATUS"])
y = df2["CASE_STATUS"]

In [160]:
for i in X.select_dtypes(include=[object]).columns:
    try:
        X[i]=le.fit_transform(X[i])
        print(i)
    except:
        print('FO')

FO
FO
FO
FO
AGENT_ATTORNEY_NAME
FO
FO
FO
FO
FO
FO
FO
FO
FO
FO
FO
FO

In [161]:
X

,VISA_CLASS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,TOTAL_WORKERS,...,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE,Time_to_Review,Emp_Time
0,1,DISCOVER PRODUCTS INC.,60015,2244050900,Y,1580,ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,1,...,2015.0,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,60015,220.0,1095.0
1,1,DFS SERVICES LLC,60015,2244050900,Y,1580,SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,1,...,2015.0,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,60015,211.0,1095.0
2,1,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,699,.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,2,...,2015.0,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,20007,205.0,1095.0
3,1,INFO SERVICES LLC,48152,7343776007,N,0,PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,07302,3.0,1094.0
4,1,BB&T CORPORATION,27893,2522462031,Y,5254,ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,1,...,2015.0,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,10036,588.0,1096.0
5,1,"SUNTRUST BANKS, INC.",30308,4048137888,Y,5254,CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,1,...,2015.0,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,30303,570.0,1096.0
6,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,0,BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,08837,220.0,1094.0
7,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,0,PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,08837,220.0,1094.0
8,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,0,PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,10005,218.0,1094.0
9,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,0,MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,1,...,2015.0,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,08830,217.0,1092.0
10,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,0,PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,10010,216.0,1095.0
11,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,0,BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,08540,193.0,1093.0
12,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,0,SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,08901,193.0,1093.0
13,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,0,SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,08901,193.0,1093.0
14,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,0,ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,08901,193.0,1093.0
15,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,0,SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,08901,192.0,1092.0
16,1,ITAS INC,46240,3175758950,Y,5317,COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,1,...,2016.0,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,11747,0.0,1094.0
17,1,BATTELLE,99354,5093753959,N,0,POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,99354,1112.0,1095.0
18,1,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,0,SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,77099,1111.0,1095.0
19,1,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,0,FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,76710,1111.0,1095.0
20,1,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,2385,PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2013.0,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,95035,1106.0,1095.0
21,1,BATTELLE,99354,5093753959,N,0,POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,99354,1081.0,1095.0
22,1,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,0,POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,1,...,2013.0,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,97239,1078.0,1095.0
23,1,GIMMAL LLC,77046,7135866500,Y,4552,MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,1,...,2013.0,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,77046,1075.0,1095.0
24,1,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,0,SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,76040,1034.0,1095.0
25,1,"PLANTRONICS, INC.",95060,8314584458,Y,1505,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,1,...,2013.0,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,78704,1015.0,1095.0
26,1,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,0,POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,60637,1015.0,1095.0
27,1,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,0,POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2014.0,0,47244.00,0.0,Year,N,N,90095,952.0,1095.0
28,1,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,1332,ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,1,...,2013.0,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,45236,950.0,1095.0
29,1,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,0,POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,99164,949.0,1095.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,0,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,0,ANALYST,FINANCIAL ANALYSTS,523110,1,...,2017.0,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,0,0,10019,1.0,730.0
624621,1,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,0,STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,76117,1.0,1095.0
624622,1,"NTT DATA SERVICES, LLC",75075,0,0,0,ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624623,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,0,SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,60007,0.0,759.0
624624,1,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,0,COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,49423,0.0,214.0
624625,1,"NTT DATA SERVICES, LLC",75075,0,0,0,ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624626,1,PHILIPS NORTH AMERICA LLC,01810,0,0,0,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,1,...,2017.0,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,94588-3050,0.0,1095.0
624627,1,"AMPCUS, INC.",20151,0,0,0,BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,20190,0.0,1095.0
624628,1,VIGILANT TECHNOLOGIES LLC,48084,0,0,0,ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,48084,0.0,1095.0
624629,1,"ZUORA, INC.",94403,0,0,0,REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,95134,0.0,1095.0
624630,1,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,0,STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2017.0,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,63110,0.0,364.0
624631,1,"ARTEMIS CONSULTING, INC.",22181,0,0,0,APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,20002,0.0,1095.0
624632,1,BANK OF AMERICA N.A.,10020,0,0,0,ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,1,...,2017.0,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,10036,0.0,1096.0
624633,1,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,0,SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,1,...,2017.0,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,77032,0.0,1040.0
624634,1,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,0,SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,1,...,2017.0,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,94088,0.0,1095.0
624635,1,CONSUMERINFO.COM,92626,0,0,0,SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,1,...,2017.0,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,92626,0.0,1095.0
624636,1,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,0,PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,1,...,2017.0,0,87000.00,0.0,Year,N,N,90027,0.0,729.0
624637,1,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,0,DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,1,...,2017.0,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,90245,0.0,1095.0
624638,1,"HCL AMERICA, INC.",94085,0,0,0,PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,20,...,2017.0,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,55112,0.0,1095.0
624639,1,TECHNOSOFT GROUP INC,75062,0,0,0,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,55121,0.0,1095.0
624640,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,0,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,02472,0.0,1096.0
624641,1,"CASA SYSTEMS, INC.",01810,0,0,0,TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,1,...,2017.0,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,01810,0.0,1095.0
624642,1,"STLPORT CONSULTING, INC.",94043,0,0,0,GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,1,...,2014.0,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,94043,880.0,1095.0
624643,1,"STLPORT CONSULTING, INC.",94043,0,0,0,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,792.0,1095.0
624644,1,"STLPORT CONSULTING, INC.",94043,0,0,0,SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,781.0,1085.0
624645,1,FAST SWITCH LTD,43017,0,0,0,SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,43017,451.0,1094.0
624646,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,0,POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,02139,6.0,364.0
624647,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,0,RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,1,...,2016.0,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,02139,7.0,364.0
624648,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,0,POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,02139,6.0,364.0
624649,1,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,1080,EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,1,...,2016.0,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,90210,6.0,1096.0

In [163]:
X

,VISA_CLASS,EMPLOYER_NAME,EMPLOYER_POSTAL_CODE,EMPLOYER_PHONE,AGENT_REPRESENTING_EMPLOYER,AGENT_ATTORNEY_NAME,JOB_TITLE,SOC_NAME,NAICS_CODE,TOTAL_WORKERS,...,PW_SOURCE_YEAR,PW_SOURCE_OTHER,WAGE_RATE_OF_PAY_FROM,WAGE_RATE_OF_PAY_TO,WAGE_UNIT_OF_PAY,H1B_DEPENDENT,WILLFUL_VIOLATOR,WORKSITE_POSTAL_CODE,Time_to_Review,Emp_Time
0,1,DISCOVER PRODUCTS INC.,60015,2244050900,Y,"ELLSWORTH, CHAD",ASSOCIATE DATA INTEGRATION,COMPUTER SYSTEMS ANALYSTS,522210,1,...,2015.0,OFLC ONLINE DATA CENTER,65811.00,67320.0,Year,N,N,60015,220.0,1095.0
1,1,DFS SERVICES LLC,60015,2244050900,Y,"ELLSWORTH, CHAD",SENIOR ASSOCIATE,OPERATIONS RESEARCH ANALYSTS,522210,1,...,2015.0,TOWERS WATSON DATA SERVICES 2015 CSR PROFESSIO...,53000.00,57200.0,Year,N,N,60015,211.0,1095.0
2,1,EASTBANC TECHNOLOGIES LLC,20007,2022953000,Y,"BURKE, KAREN",.NET SOFTWARE PROGRAMMER,COMPUTER PROGRAMMERS,541511,2,...,2015.0,OFLC ONLINE DATA CENTER,77000.00,0.0,Year,Y,N,20007,205.0,1095.0
3,1,INFO SERVICES LLC,48152,7343776007,N,",",PROJECT MANAGER,"COMPUTER OCCUPATIONS, ALL OTHER",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,102000.00,0.0,Year,Y,N,07302,3.0,1094.0
4,1,BB&T CORPORATION,27893,2522462031,Y,"SCOFIELD, EILEEN",ASSOCIATE - ESOTERIC ASSET BACKED SECURITIES,CREDIT ANALYSTS,522110,1,...,2015.0,OFLC ONLINE DATA CENTER,132500.00,0.0,Year,N,N,10036,588.0,1096.0
5,1,"SUNTRUST BANKS, INC.",30308,4048137888,Y,"SCOFIELD, EILEEN",CREDIT RISK METRICS SPECIALIST,"FINANCIAL SPECIALISTS, ALL OTHER",522110,1,...,2015.0,OFLC ONLINE DATA CENTER,71750.00,0.0,Year,N,N,30303,570.0,1096.0
6,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",BUSINESS SYSTEMS ANALYST,MANAGEMENT ANALYSTS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,61000.00,0.0,Year,Y,N,08837,220.0,1094.0
7,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60500.00,0.0,Year,Y,N,08837,220.0,1094.0
8,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60450.00,0.0,Year,Y,N,10005,218.0,1094.0
9,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",MARKET RESEARCH ANALYST,MARKET RESEARCH ANALYSTS AND MARKETING SPECIAL...,541511,1,...,2015.0,ONLINE WAGE LIBRARY,50000.00,0.0,Year,Y,N,08830,217.0,1092.0
10,1,CITADEL INFORMATION SERVICES INC.,08830,7322380072,N,",",PROGRAMMER ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60400.00,0.0,Year,Y,N,10010,216.0,1095.0
11,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",BUSINESS ANALYST,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,63200.00,0.0,Year,Y,N,08540,193.0,1093.0
12,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SAP BASIS ADMINISTRATOR,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60100.00,0.0,Year,Y,N,08901,193.0,1093.0
13,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,64000.00,0.0,Year,Y,N,08901,193.0,1093.0
14,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",ORACLE APPLICATION CONSULTANT,COMPUTER PROGRAMMERS,541511,1,...,2015.0,ONLINE WAGE LIBRARY,60000.00,0.0,Year,Y,N,08901,193.0,1093.0
15,1,ADVANCED TECHNOLOGY GROUP USA INC,08536,6092695555,N,",",SOFTWARE DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2015.0,ONLINE WAGE LIBRARY,65000.00,0.0,Year,Y,N,08901,192.0,1092.0
16,1,ITAS INC,46240,3175758950,Y,"SHAH, JATIN",COMPUTER SYSTEM ANALYST,COMPUTER SYSTEMS ANALYSTS,541519,1,...,2016.0,OFLC ONLINE DATA CENTER,55000.00,0.0,Year,N,N,11747,0.0,1094.0
17,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,60000.00,0.0,Year,N,N,99354,1112.0,1095.0
18,1,HARMONY SCIENCE ACADEMY-HOUSTON HIGH,77099,7134920214,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,43110.00,0.0,Year,N,N,77099,1111.0,1095.0
19,1,HARMONY SCIENCE ACADEMY-WACO,76710,2547517878,N,",",FOREIGN LANGUAGE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,38970.00,0.0,Year,N,N,76710,1111.0,1095.0
20,1,"IDC TECHNOLOGIES, INC.",95035,4083830155,Y,"HO, WAI CHI",PROGRAMMER ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2013.0,OFLC ONLINE DATA CENTER,104000.00,0.0,Year,Y,N,95035,1106.0,1095.0
21,1,BATTELLE,99354,5093753959,N,",",POST DOCTORATE RESEARCH ASSOCIATE,"BIOLOGICAL SCIENTISTS, ALL OTHER",541700,1,...,2013.0,FOREIGN LABOR CERTIFICATION DATA CENTER,28.85,0.0,Hour,N,N,99354,1081.0,1095.0
22,1,OREGON HEALTH & SCIENCE UNIVERSITY,97239,5034942169,N,",",POSTDOCTORAL RESEARCHER,"BIOLOGICAL SCIENTISTS, ALL OTHER",611310,1,...,2013.0,OFLC ONLINE DATA CENTER,40706.00,0.0,Year,N,N,97239,1078.0,1095.0
23,1,GIMMAL LLC,77046,7135866500,Y,"PEREZ, JR., JOSE",MANAGING CONSULTANT - SHAREPOINT DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",5416,1,...,2013.0,OFLC ONLINE DATA CENTER,78000.00,0.0,Year,N,N,77046,1075.0,1095.0
24,1,HARMONY SCIENCE ACADEMY-EULESS,76040,8173543000,N,",",SCIENCE TEACHER,"SECONDARY SCHOOL TEACHERS, EXCEPT SPECIAL AND",611110,1,...,2013.0,OFLC ONLINE DATA CENTER,45540.00,0.0,Year,N,N,76040,1034.0,1095.0
25,1,"PLANTRONICS, INC.",95060,8314584458,Y,"DUONG, DAVID",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334220,1,...,2013.0,OFLC ONLINE DATA CENTER,66331.00,95000.0,Year,N,N,78704,1015.0,1095.0
26,1,THE UNIVERSITY OF CHICAGO,60637,7737027752,N,",",POSTDOCTORAL SCHOLAR,BIOCHEMISTS AND BIOPHYSICISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,39611.00,0.0,Year,N,N,60637,1015.0,1095.0
27,1,"UNIVERSITY OF CALIFORNIA, LOS ANGELES",90095,3108251681,N,",",POSTDOCTORAL SCHOLAR,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2014.0,0,47244.00,0.0,Year,N,N,90095,952.0,1095.0
28,1,"AXCESS FINANCIAL SERVICES, INC.",45236,5132296469,Y,"DECURTIS, DANIEL",ANALYST - MARKETING ANALYTICS,STATISTICIANS,5239,1,...,2013.0,OFLC ONLINE DATA CENTER,70000.00,0.0,Year,N,N,45236,950.0,1095.0
29,1,WASHINGTON STATE UNIVERSITY,99164,5093354508,N,",",POSTDOCTORAL RESEARCH ASSOCIATE,SOIL AND PLANT SCIENTISTS,611310,1,...,2013.0,OFLC ONLINE DATA CENTER,41600.00,0.0,Year,N,N,99164,949.0,1095.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
624620,0,ELLIOTT MANAGEMENT CORPORATION,10019,0,0,",",ANALYST,FINANCIAL ANALYSTS,523110,1,...,2017.0,OFLC ONLINE DATA CENTER,125000.00,0.0,Year,0,0,10019,1.0,730.0
624621,1,I NET SOFTWARE TECHNOLOGIES INC,75063,0,0,",",STORAGE (SAN) ADMINISTRATOR,NETWORK AND COMPUTER SYSTEMS ADMINISTRATORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,55.00,65.0,Hour,Y,N,76117,1.0,1095.0
624622,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNIG SENIOR ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624623,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,75100.00,0.0,Year,Y,N,60007,0.0,759.0
624624,1,AVANI TECHNOLOGY SOLUTIONS INC.,14606,0,0,",",COMPUTER SYSTEMS ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,82000.00,0.0,Year,Y,N,49423,0.0,214.0
624625,1,"NTT DATA SERVICES, LLC",75075,0,0,",",ENTERPRISE RESOURCE PLANNING ADVISOR,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,112528.00,142528.0,Year,N,N,75039,0.0,1095.0
624626,1,PHILIPS NORTH AMERICA LLC,01810,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",334419,1,...,2017.0,OFLC ONLINE DATA CENTER,145285.00,0.0,Year,N,N,94588-3050,0.0,1095.0
624627,1,"AMPCUS, INC.",20151,0,0,",",BUSINESS DATA ANALYST,COMPUTER SYSTEMS ANALYSTS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,102731.00,0.0,Year,N,N,20190,0.0,1095.0
624628,1,VIGILANT TECHNOLOGIES LLC,48084,0,0,",",ORACLE APPLICATION ENGINEER (OBIEE),"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,72000.00,0.0,Year,Y,N,48084,0.0,1095.0
624629,1,"ZUORA, INC.",94403,0,0,",",REVENUE ANALYST,ACCOUNTANTS AND AUDITORS,541511,1,...,2017.0,OFLC ONLINE DATA CENTER,110000.00,0.0,Year,N,N,95134,0.0,1095.0
624630,1,WASHINGTON UNIVERSITY IN ST. LOUIS,63130,0,0,",",STAFF SCIENTIST,"MEDICAL SCIENTISTS, EXCEPT EPIDEMIOLOGISTS",611310,1,...,2017.0,OFLC ONLINE DATA CENTER,47476.00,0.0,Year,N,N,63110,0.0,364.0
624631,1,"ARTEMIS CONSULTING, INC.",22181,0,0,",",APPLICATION DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,105000.00,0.0,Year,N,N,20002,0.0,1095.0
624632,1,BANK OF AMERICA N.A.,10020,0,0,",",ASSISTANT VICE PRESIDENT; INVESTMENT STRATEGIST I,OPERATIONS RESEARCH ANALYSTS,522110,1,...,2017.0,OFLC ONLINE DATA CENTER,98000.00,0.0,Year,N,N,10036,0.0,1096.0
624633,1,"HALLIBURTON ENERGY SERVICES, INC.",77032,0,0,",",SR. TECHNICAL PROFESSIONAL - MECHANICAL,MECHANICAL ENGINEERS,541330,1,...,2017.0,DIETRICH 2017 ENGINEERING SALARY SURVEY,88500.00,0.0,Year,N,N,77032,0.0,1040.0
624634,1,"ADVANCED MICRO DEVICES, INC.",94088-3453,0,0,",",SENIOR FINANCIAL ACCOUNTANT,ACCOUNTANTS AND AUDITORS,334413,1,...,2017.0,RADFORD GLOBAL TECHNOLOGY SURVEY,90377.00,122600.0,Year,N,N,94088,0.0,1095.0
624635,1,CONSUMERINFO.COM,92626,0,0,",",SOFTWARE DEVELOPER EXPERT,"SOFTWARE DEVELOPERS, APPLICATIONS",5191,1,...,2017.0,TOWERS WATSON DATA SERVICES INFORMATION TECHNO...,128000.00,0.0,Year,N,N,92626,0.0,1095.0
624636,1,"MICHAEL MALTZAN ARCHITECTURE, INC.",90027,0,0,",",PROJECT ARCHITECT,"ARCHITECTS, EXCEPT LANDSCAPE AND NAVAL",541310,1,...,2017.0,0,87000.00,0.0,Year,N,N,90027,0.0,729.0
624637,1,L&T TECHNOLOGY SERVICES LIMITED,08817,0,0,",",DESIGN ENGINEER,COMMERCIAL AND INDUSTRIAL DESIGNERS,541330,1,...,2017.0,OFLC ONLINE DATA CENTER,64000.00,74000.0,Year,Y,N,90245,0.0,1095.0
624638,1,"HCL AMERICA, INC.",94085,0,0,",",PROJECT MANAGER - III,COMPUTER PROGRAMMERS,541511,20,...,2017.0,OFLC ONLINE DATA CENTER,88462.00,0.0,Year,Y,N,55112,0.0,1095.0
624639,1,TECHNOSOFT GROUP INC,75062,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,78700.00,0.0,Year,Y,N,55121,0.0,1095.0
624640,1,"FRONTIER TECHNOLOGIES, LLC",60563,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2017.0,OFLC ONLINE DATA CENTER,87864.00,0.0,Year,Y,N,02472,0.0,1096.0
624641,1,"CASA SYSTEMS, INC.",01810,0,0,",",TECHNICAL SUPPORT ENGINEER,COMPUTER NETWORK SUPPORT SPECIALISTS,334290,1,...,2017.0,THE SURVEY GROUP: BENCHMARK COMPENSATION SURVEY,67000.00,70000.0,Year,N,N,01810,0.0,1095.0
624642,1,"STLPORT CONSULTING, INC.",94043,0,0,",",GRAPHIC DESIGNER,GRAPHIC DESIGNERS,5112,1,...,2014.0,FLC ONLINE WAGE LIBRARY,28.50,0.0,Hour,N,N,94043,880.0,1095.0
624643,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,792.0,1095.0
624644,1,"STLPORT CONSULTING, INC.",94043,0,0,",",SOFTWARE ENGINEER,"SOFTWARE DEVELOPERS, APPLICATIONS",5112,1,...,2015.0,OFLC ONLINE DATA CENTER,57.86,0.0,Hour,N,N,94043,781.0,1085.0
624645,1,FAST SWITCH LTD,43017,0,0,",",SENIOR JAVA DEVELOPER,"SOFTWARE DEVELOPERS, APPLICATIONS",541511,1,...,2016.0,OFLC ONLINE DATA CENTER,46.00,0.0,Hour,Y,N,43017,451.0,1094.0
624646,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,PHYSICISTS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,60400.00,0.0,Year,N,N,02139,6.0,364.0
624647,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",RESEARCH SCIENTIST,"GEOSCIENTISTS, EXCEPT HYDROLOGISTS AND GEOGRAP...",6113,1,...,2016.0,OFLC ONLINE DATA CENTER,65000.00,0.0,Year,N,N,02139,7.0,364.0
624648,1,MASSACHUSETTS INSTITUTE OF TECHNOLOGY,02139,6.17253e+09,N,",",POSTDOCTORAL ASSOCIATE,MATERIALS ENGINEERS,6113,1,...,2016.0,OFLC ONLINE DATA CENTER,49383.00,0.0,Year,N,N,02139,6.0,364.0
624649,1,"PARK VIEW TRAVEL BEVERLY HILLS, LLC",90210,3.10286e+09,Y,"CHUN-FRUTO, EILEEN",EVENTS AND INCENTIVES COORDINATOR,"MEETING, CONVENTION, AND EVENT PLANNERS",5615,1,...,2016.0,OFLC ONLINE DATA CENTER,45200.00,0.0,Year,N,N,90210,6.0,1096.0